# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AddMcpClientRequest do
  @moduledoc """
  MCP client configuration for creating a new client (tool_pricing not available at creation). The schema varies based on connection_type: - HTTP/SSE: connection_string is required - STDIO: stdio_config is required - InProcess: server instance must be provided programmatically (Go package only) 
  """

  @derive JSON.Encoder
  defstruct [
    :client_id,
    :name,
    :is_code_mode_client,
    :is_ping_available,
    :connection_type,
    :auth_type,
    :oauth_config_id,
    :headers,
    :oauth_config,
    :tools_to_execute,
    :tools_to_auto_execute,
    :allow_on_all_virtual_keys,
    :tls_config,
    :per_user_header_keys,
    :user_headers,
    :connection_string,
    :stdio_config
  ]

  @type t :: %__MODULE__{
          :client_id => any() | nil,
          :name => any(),
          :is_code_mode_client => any() | nil,
          :is_ping_available => any() | nil,
          :connection_type => any(),
          :auth_type => any() | nil,
          :oauth_config_id => any() | nil,
          :headers => %{optional(String.t()) => any()} | nil,
          :oauth_config => ExBifrost.Model.OAuthConfigRequest.t() | nil,
          :tools_to_execute => [any()] | nil,
          :tools_to_auto_execute => [any()] | nil,
          :allow_on_all_virtual_keys => any() | nil,
          :tls_config => ExBifrost.Model.AddMcpClientRequestOneOfAllOfTlsConfig.t() | nil,
          :per_user_header_keys => [any()] | nil,
          :user_headers => %{optional(String.t()) => any()} | nil,
          :connection_string => any(),
          :stdio_config => ExBifrost.Model.AddMcpClientRequestOneOf2AllOfStdioConfig.t()
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:oauth_config, :struct, ExBifrost.Model.OAuthConfigRequest)
    |> Deserializer.deserialize(:tls_config, :struct, ExBifrost.Model.AddMcpClientRequestOneOfAllOfTlsConfig)
    |> Deserializer.deserialize(:stdio_config, :struct, ExBifrost.Model.AddMcpClientRequestOneOf2AllOfStdioConfig)
  end
end
