# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AnthropicCreateMessage200Response do
  @moduledoc """
  AnthropicCreateMessage200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :type,
    :message,
    :index,
    :content_block,
    :delta,
    :usage,
    :error
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :type => String.t() | nil,
          :message => ExBifrost.Model.AnthropicMessageResponse.t() | nil,
          :index => integer() | nil,
          :content_block => ExBifrost.Model.AnthropicContentBlock.t() | nil,
          :delta => ExBifrost.Model.AnthropicCreateMessage200ResponseDelta.t() | nil,
          :usage => ExBifrost.Model.AnthropicCreateMessage200ResponseUsage.t() | nil,
          :error => ExBifrost.Model.AnthropicCreateMessage200ResponseError.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:message, :struct, ExBifrost.Model.AnthropicMessageResponse)
    |> Deserializer.deserialize(:content_block, :struct, ExBifrost.Model.AnthropicContentBlock)
    |> Deserializer.deserialize(:delta, :struct, ExBifrost.Model.AnthropicCreateMessage200ResponseDelta)
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.AnthropicCreateMessage200ResponseUsage)
    |> Deserializer.deserialize(:error, :struct, ExBifrost.Model.AnthropicCreateMessage200ResponseError)
  end
end
