# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AnthropicCountTokens200Response do
  @moduledoc """
  AnthropicCountTokens200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :input_tokens
  ]

  @type t :: %__MODULE__{
          :input_tokens => integer() | nil
        }

  def decode(value) do
    value
  end
end
