# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AnthropicContentBlock do
  @moduledoc """
  AnthropicContentBlock model.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :text,
    :thinking,
    :signature,
    :data,
    :tool_use_id,
    :id,
    :name,
    :input,
    :server_name,
    :content,
    :source,
    :cache_control,
    :citations,
    :context,
    :title
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :text => String.t() | nil,
          :thinking => String.t() | nil,
          :signature => String.t() | nil,
          :data => String.t() | nil,
          :tool_use_id => String.t() | nil,
          :id => String.t() | nil,
          :name => String.t() | nil,
          :input => map() | nil,
          :server_name => String.t() | nil,
          :content => ExBifrost.Model.AnthropicMessageRequestSystem.t() | nil,
          :source => ExBifrost.Model.AnthropicContentBlockSource.t() | nil,
          :cache_control => ExBifrost.Model.CacheControl.t() | nil,
          :citations => ExBifrost.Model.AnthropicContentBlockCitations.t() | nil,
          :context => String.t() | nil,
          :title => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:content, :struct, ExBifrost.Model.AnthropicMessageRequestSystem)
    |> Deserializer.deserialize(:source, :struct, ExBifrost.Model.AnthropicContentBlockSource)
    |> Deserializer.deserialize(:cache_control, :struct, ExBifrost.Model.CacheControl)
    |> Deserializer.deserialize(:citations, :struct, ExBifrost.Model.AnthropicContentBlockCitations)
  end
end
