# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AnthropicTextRequest do
  @moduledoc """
  AnthropicTextRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :prompt,
    :max_tokens_to_sample,
    :stream,
    :temperature,
    :top_p,
    :top_k,
    :stop_sequences,
    :fallbacks
  ]

  @type t :: %__MODULE__{
          :model => String.t(),
          :prompt => String.t(),
          :max_tokens_to_sample => integer(),
          :stream => boolean() | nil,
          :temperature => number() | nil,
          :top_p => number() | nil,
          :top_k => integer() | nil,
          :stop_sequences => [String.t()] | nil,
          :fallbacks => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
