# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AnthropicListModelsResponse do
  @moduledoc """
  AnthropicListModelsResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :has_more,
    :first_id,
    :last_id
  ]

  @type t :: %__MODULE__{
          :data => [ExBifrost.Model.AnthropicListModelsResponseDataInner.t()] | nil,
          :has_more => boolean() | nil,
          :first_id => String.t() | nil,
          :last_id => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:data, :list, ExBifrost.Model.AnthropicListModelsResponseDataInner)
  end
end
