# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AnthropicCreateMessage200ResponseUsageCacheCreation do
  @moduledoc """
  AnthropicCreateMessage200ResponseUsageCacheCreation model.
  """

  @derive JSON.Encoder
  defstruct [
    :ephemeral_5m_input_tokens,
    :ephemeral_1h_input_tokens
  ]

  @type t :: %__MODULE__{
          :ephemeral_5m_input_tokens => integer() | nil,
          :ephemeral_1h_input_tokens => integer() | nil
        }

  def decode(value) do
    value
  end
end
