# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AsyncJobResponse do
  @moduledoc """
  Response returned when creating or polling an async job
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :status,
    :expires_at,
    :created_at,
    :completed_at,
    :status_code,
    :result,
    :error
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :status => ExBifrost.Model.AsyncJobStatus.t(),
          :expires_at => DateTime.t() | nil,
          :created_at => DateTime.t(),
          :completed_at => DateTime.t() | nil,
          :status_code => integer() | nil,
          :result => any() | nil,
          :error => ExBifrost.Model.BifrostError.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:status, :struct, ExBifrost.Model.AsyncJobStatus)
    |> Deserializer.deserialize(:error, :struct, ExBifrost.Model.BifrostError)
  end
end
