# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AuditEvent do
  @moduledoc """
  A CADF-compliant audit event.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :typeURI,
    :eventType,
    :eventTime,
    :action,
    :outcome,
    :initiator,
    :target,
    :observer,
    :reason,
    :attachments,
    :tags,
    :requestMethod,
    :requestPath,
    :requestIP,
    :userAgent,
    :duration,
    :signature,
    :createdAt
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :typeURI => String.t(),
          :eventType => ExBifrost.Model.AuditEventType.t(),
          :eventTime => DateTime.t(),
          :action => ExBifrost.Model.AuditAction.t(),
          :outcome => ExBifrost.Model.AuditOutcome.t(),
          :initiator => ExBifrost.Model.AuditResource.t(),
          :target => ExBifrost.Model.AuditResource.t(),
          :observer => ExBifrost.Model.AuditResource.t(),
          :reason => ExBifrost.Model.AuditReason.t() | nil,
          :attachments => [ExBifrost.Model.AuditAttachment.t()] | nil,
          :tags => [String.t()] | nil,
          :requestMethod => String.t() | nil,
          :requestPath => String.t() | nil,
          :requestIP => String.t() | nil,
          :userAgent => String.t() | nil,
          :duration => integer() | nil,
          :signature => String.t(),
          :createdAt => DateTime.t()
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:eventType, :struct, ExBifrost.Model.AuditEventType)
    |> Deserializer.deserialize(:action, :struct, ExBifrost.Model.AuditAction)
    |> Deserializer.deserialize(:outcome, :struct, ExBifrost.Model.AuditOutcome)
    |> Deserializer.deserialize(:initiator, :struct, ExBifrost.Model.AuditResource)
    |> Deserializer.deserialize(:target, :struct, ExBifrost.Model.AuditResource)
    |> Deserializer.deserialize(:observer, :struct, ExBifrost.Model.AuditResource)
    |> Deserializer.deserialize(:reason, :struct, ExBifrost.Model.AuditReason)
    |> Deserializer.deserialize(:attachments, :list, ExBifrost.Model.AuditAttachment)
  end
end
