# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AuditReason do
  @moduledoc """
  The CADF reason for an outcome (especially for failures).
  """

  @derive JSON.Encoder
  defstruct [
    :reasonCode,
    :reasonType,
    :message
  ]

  @type t :: %__MODULE__{
          :reasonCode => String.t() | nil,
          :reasonType => String.t() | nil,
          :message => String.t() | nil
        }

  def decode(value) do
    value
  end
end
