# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.AuditLogResponse do
  @moduledoc """
  Response wrapper for a single audit log entry.
  """

  @derive JSON.Encoder
  defstruct [
    :audit_log
  ]

  @type t :: %__MODULE__{
          :audit_log => ExBifrost.Model.AuditEvent.t()
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:audit_log, :struct, ExBifrost.Model.AuditEvent)
  end
end
