# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BatchCreateRequest do
  @moduledoc """
  BatchCreateRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :input_file_id,
    :requests,
    :endpoint,
    :completion_window,
    :metadata
  ]

  @type t :: %__MODULE__{
          :model => String.t(),
          :input_file_id => String.t() | nil,
          :requests => [ExBifrost.Model.BatchCreateRequestRequestsInner.t()] | nil,
          :endpoint => String.t() | nil,
          :completion_window => String.t() | nil,
          :metadata => %{optional(String.t()) => String.t()} | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:requests, :list, ExBifrost.Model.BatchCreateRequestRequestsInner)
  end
end
