# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BatchRetrieveResponse do
  @moduledoc """
  BatchRetrieveResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :object,
    :endpoint,
    :input_file_id,
    :completion_window,
    :status,
    :request_counts,
    :metadata,
    :created_at,
    :expires_at,
    :in_progress_at,
    :finalizing_at,
    :completed_at,
    :failed_at,
    :expired_at,
    :cancelling_at,
    :cancelled_at,
    :output_file_id,
    :error_file_id,
    :errors,
    :processing_status,
    :results_url,
    :archived_at,
    :operation_name,
    :done,
    :progress,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :object => String.t() | nil,
          :endpoint => String.t() | nil,
          :input_file_id => String.t() | nil,
          :completion_window => String.t() | nil,
          :status => String.t() | nil,
          :request_counts => ExBifrost.Model.CancelBatch200ResponseRequestCounts.t() | nil,
          :metadata => %{optional(String.t()) => String.t()} | nil,
          :created_at => integer() | nil,
          :expires_at => integer() | nil,
          :in_progress_at => integer() | nil,
          :finalizing_at => integer() | nil,
          :completed_at => integer() | nil,
          :failed_at => integer() | nil,
          :expired_at => integer() | nil,
          :cancelling_at => integer() | nil,
          :cancelled_at => integer() | nil,
          :output_file_id => String.t() | nil,
          :error_file_id => String.t() | nil,
          :errors => ExBifrost.Model.BatchRetrieveResponseErrors.t() | nil,
          :processing_status => String.t() | nil,
          :results_url => String.t() | nil,
          :archived_at => integer() | nil,
          :operation_name => String.t() | nil,
          :done => boolean() | nil,
          :progress => integer() | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:request_counts, :struct, ExBifrost.Model.CancelBatch200ResponseRequestCounts)
    |> Deserializer.deserialize(:errors, :struct, ExBifrost.Model.BatchRetrieveResponseErrors)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
