# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockConverseRequestToolConfig do
  @moduledoc """
  BedrockConverseRequestToolConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :tools,
    :toolChoice
  ]

  @type t :: %__MODULE__{
          :tools => [ExBifrost.Model.BedrockConverseRequestToolConfigToolsInner.t()] | nil,
          :toolChoice => ExBifrost.Model.BedrockConverseRequestToolConfigToolChoice.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:tools, :list, ExBifrost.Model.BedrockConverseRequestToolConfigToolsInner)
    |> Deserializer.deserialize(:toolChoice, :struct, ExBifrost.Model.BedrockConverseRequestToolConfigToolChoice)
  end
end
