# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockConverseRequest do
  @moduledoc """
  BedrockConverseRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :messages,
    :system,
    :inferenceConfig,
    :toolConfig,
    :guardrailConfig,
    :additionalModelRequestFields,
    :additionalModelResponseFieldPaths,
    :performanceConfig,
    :promptVariables,
    :requestMetadata,
    :serviceTier,
    :fallbacks
  ]

  @type t :: %__MODULE__{
          :messages => [ExBifrost.Model.BedrockMessage.t()] | nil,
          :system => [ExBifrost.Model.BedrockConverseRequestSystemInner.t()] | nil,
          :inferenceConfig => ExBifrost.Model.BedrockConverseRequestInferenceConfig.t() | nil,
          :toolConfig => ExBifrost.Model.BedrockConverseRequestToolConfig.t() | nil,
          :guardrailConfig => ExBifrost.Model.BedrockConverseRequestGuardrailConfig.t() | nil,
          :additionalModelRequestFields => map() | nil,
          :additionalModelResponseFieldPaths => [String.t()] | nil,
          :performanceConfig => ExBifrost.Model.BedrockConverseRequestPerformanceConfig.t() | nil,
          :promptVariables =>
            %{optional(String.t()) => ExBifrost.Model.BedrockConverseRequestPromptVariablesValue.t()} | nil,
          :requestMetadata => %{optional(String.t()) => String.t()} | nil,
          :serviceTier => ExBifrost.Model.BedrockConverseRequestServiceTier.t() | nil,
          :fallbacks => [String.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:messages, :list, ExBifrost.Model.BedrockMessage)
    |> Deserializer.deserialize(:system, :list, ExBifrost.Model.BedrockConverseRequestSystemInner)
    |> Deserializer.deserialize(:inferenceConfig, :struct, ExBifrost.Model.BedrockConverseRequestInferenceConfig)
    |> Deserializer.deserialize(:toolConfig, :struct, ExBifrost.Model.BedrockConverseRequestToolConfig)
    |> Deserializer.deserialize(:guardrailConfig, :struct, ExBifrost.Model.BedrockConverseRequestGuardrailConfig)
    |> Deserializer.deserialize(:performanceConfig, :struct, ExBifrost.Model.BedrockConverseRequestPerformanceConfig)
    |> Deserializer.deserialize(:promptVariables, :map, ExBifrost.Model.BedrockConverseRequestPromptVariablesValue)
    |> Deserializer.deserialize(:serviceTier, :struct, ExBifrost.Model.BedrockConverseRequestServiceTier)
  end
end
