# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockContentBlock do
  @moduledoc """
  BedrockContentBlock model.
  """

  @derive JSON.Encoder
  defstruct [
    :text,
    :image,
    :document,
    :toolUse,
    :toolResult,
    :guardContent,
    :reasoningContent,
    :json,
    :cachePoint
  ]

  @type t :: %__MODULE__{
          :text => String.t() | nil,
          :image => ExBifrost.Model.BedrockContentBlockImage.t() | nil,
          :document => ExBifrost.Model.BedrockContentBlockDocument.t() | nil,
          :toolUse => ExBifrost.Model.BedrockContentBlockToolUse.t() | nil,
          :toolResult => ExBifrost.Model.BedrockContentBlockToolResult.t() | nil,
          :guardContent => ExBifrost.Model.BedrockConverseRequestSystemInnerGuardContent.t() | nil,
          :reasoningContent => ExBifrost.Model.BedrockContentBlockReasoningContent.t() | nil,
          :json => map() | nil,
          :cachePoint => ExBifrost.Model.BedrockConverseRequestSystemInnerCachePoint.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:image, :struct, ExBifrost.Model.BedrockContentBlockImage)
    |> Deserializer.deserialize(:document, :struct, ExBifrost.Model.BedrockContentBlockDocument)
    |> Deserializer.deserialize(:toolUse, :struct, ExBifrost.Model.BedrockContentBlockToolUse)
    |> Deserializer.deserialize(:toolResult, :struct, ExBifrost.Model.BedrockContentBlockToolResult)
    |> Deserializer.deserialize(:guardContent, :struct, ExBifrost.Model.BedrockConverseRequestSystemInnerGuardContent)
    |> Deserializer.deserialize(:reasoningContent, :struct, ExBifrost.Model.BedrockContentBlockReasoningContent)
    |> Deserializer.deserialize(:cachePoint, :struct, ExBifrost.Model.BedrockConverseRequestSystemInnerCachePoint)
  end
end
