# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockConverseStream200Response do
  @moduledoc """
  Flat structure for streaming events matching actual Bedrock API response
  """

  @derive JSON.Encoder
  defstruct [
    :role,
    :contentBlockIndex,
    :delta,
    :stopReason,
    :start,
    :usage,
    :metrics,
    :trace,
    :additionalModelResponseFields,
    :invokeModelRawChunk
  ]

  @type t :: %__MODULE__{
          :role => String.t() | nil,
          :contentBlockIndex => integer() | nil,
          :delta => ExBifrost.Model.BedrockConverseStream200ResponseDelta.t() | nil,
          :stopReason => String.t() | nil,
          :start => ExBifrost.Model.BedrockConverseStream200ResponseStart.t() | nil,
          :usage => ExBifrost.Model.BedrockConverseStream200ResponseUsage.t() | nil,
          :metrics => ExBifrost.Model.BedrockConverseStream200ResponseMetrics.t() | nil,
          :trace => map() | nil,
          :additionalModelResponseFields => map() | nil,
          :invokeModelRawChunk => binary() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:delta, :struct, ExBifrost.Model.BedrockConverseStream200ResponseDelta)
    |> Deserializer.deserialize(:start, :struct, ExBifrost.Model.BedrockConverseStream200ResponseStart)
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.BedrockConverseStream200ResponseUsage)
    |> Deserializer.deserialize(:metrics, :struct, ExBifrost.Model.BedrockConverseStream200ResponseMetrics)
  end
end
