# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockConverseResponse do
  @moduledoc """
  BedrockConverseResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :output,
    :stopReason,
    :usage,
    :metrics,
    :additionalModelResponseFields,
    :trace,
    :performanceConfig,
    :serviceTier
  ]

  @type t :: %__MODULE__{
          :output => ExBifrost.Model.BedrockConverseResponseOutput.t() | nil,
          :stopReason => String.t() | nil,
          :usage => ExBifrost.Model.BedrockConverseStream200ResponseUsage.t() | nil,
          :metrics => ExBifrost.Model.BedrockConverseStream200ResponseMetrics.t() | nil,
          :additionalModelResponseFields => map() | nil,
          :trace => map() | nil,
          :performanceConfig => ExBifrost.Model.BedrockConverseRequestPerformanceConfig.t() | nil,
          :serviceTier => ExBifrost.Model.BedrockConverseRequestServiceTier.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:output, :struct, ExBifrost.Model.BedrockConverseResponseOutput)
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.BedrockConverseStream200ResponseUsage)
    |> Deserializer.deserialize(:metrics, :struct, ExBifrost.Model.BedrockConverseStream200ResponseMetrics)
    |> Deserializer.deserialize(:performanceConfig, :struct, ExBifrost.Model.BedrockConverseRequestPerformanceConfig)
    |> Deserializer.deserialize(:serviceTier, :struct, ExBifrost.Model.BedrockConverseRequestServiceTier)
  end
end
