# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockInvokeRequest do
  @moduledoc """
  Raw model invocation request. The body format depends on the model provider. For Anthropic models, use Anthropic format. For other models, use their native format. 
  """

  @derive JSON.Encoder
  defstruct [
    :prompt,
    :max_tokens,
    :max_tokens_to_sample,
    :temperature,
    :top_p,
    :top_k,
    :stop,
    :stop_sequences,
    :messages,
    :system,
    :anthropic_version
  ]

  @type t :: %__MODULE__{
          :prompt => String.t() | nil,
          :max_tokens => integer() | nil,
          :max_tokens_to_sample => integer() | nil,
          :temperature => number() | nil,
          :top_p => number() | nil,
          :top_k => integer() | nil,
          :stop => [String.t()] | nil,
          :stop_sequences => [String.t()] | nil,
          :messages => [map()] | nil,
          :system => ExBifrost.Model.ChatCompletionRequestStop.t() | nil,
          :anthropic_version => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:system, :struct, ExBifrost.Model.ChatCompletionRequestStop)
  end
end
