# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockContentBlockImage do
  @moduledoc """
  BedrockContentBlockImage model.
  """

  @derive JSON.Encoder
  defstruct [
    :format,
    :source
  ]

  @type t :: %__MODULE__{
          :format => String.t() | nil,
          :source => ExBifrost.Model.BedrockContentBlockImageSource.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:source, :struct, ExBifrost.Model.BedrockContentBlockImageSource)
  end
end
