# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockBatchJobRequest do
  @moduledoc """
  BedrockBatchJobRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :modelId,
    :jobName,
    :roleArn,
    :inputDataConfig,
    :outputDataConfig,
    :timeoutDurationInHours,
    :tags
  ]

  @type t :: %__MODULE__{
          :modelId => String.t() | nil,
          :jobName => String.t() | nil,
          :roleArn => String.t(),
          :inputDataConfig => ExBifrost.Model.BedrockBatchJobRequestInputDataConfig.t(),
          :outputDataConfig => ExBifrost.Model.BedrockBatchJobRequestOutputDataConfig.t(),
          :timeoutDurationInHours => integer() | nil,
          :tags => [ExBifrost.Model.BedrockBatchJobRequestTagsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:inputDataConfig, :struct, ExBifrost.Model.BedrockBatchJobRequestInputDataConfig)
    |> Deserializer.deserialize(:outputDataConfig, :struct, ExBifrost.Model.BedrockBatchJobRequestOutputDataConfig)
    |> Deserializer.deserialize(:tags, :list, ExBifrost.Model.BedrockBatchJobRequestTagsInner)
  end
end
