# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockConverseStream200ResponseDelta do
  @moduledoc """
  BedrockConverseStream200ResponseDelta model.
  """

  @derive JSON.Encoder
  defstruct [
    :text,
    :reasoningContent,
    :toolUse
  ]

  @type t :: %__MODULE__{
          :text => String.t() | nil,
          :reasoningContent => ExBifrost.Model.BedrockConverseStream200ResponseDeltaReasoningContent.t() | nil,
          :toolUse => ExBifrost.Model.BedrockConverseStream200ResponseDeltaToolUse.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :reasoningContent,
      :struct,
      ExBifrost.Model.BedrockConverseStream200ResponseDeltaReasoningContent
    )
    |> Deserializer.deserialize(:toolUse, :struct, ExBifrost.Model.BedrockConverseStream200ResponseDeltaToolUse)
  end
end
