# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockMessage do
  @moduledoc """
  BedrockMessage model.
  """

  @derive JSON.Encoder
  defstruct [
    :role,
    :content
  ]

  @type t :: %__MODULE__{
          :role => String.t(),
          :content => [ExBifrost.Model.BedrockContentBlock.t()]
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:content, :list, ExBifrost.Model.BedrockContentBlock)
  end
end
