# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockContentBlockReasoningContent do
  @moduledoc """
  BedrockContentBlockReasoningContent model.
  """

  @derive JSON.Encoder
  defstruct [
    :reasoningText
  ]

  @type t :: %__MODULE__{
          :reasoningText => ExBifrost.Model.BedrockConverseStream200ResponseDeltaReasoningContent.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :reasoningText,
      :struct,
      ExBifrost.Model.BedrockConverseStream200ResponseDeltaReasoningContent
    )
  end
end
