# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockCountTokensRequestInput do
  @moduledoc """
  BedrockCountTokensRequestInput model.
  """

  @derive JSON.Encoder
  defstruct [
    :converse
  ]

  @type t :: %__MODULE__{
          :converse => %{optional(String.t()) => any()}
        }

  def decode(value) do
    value
  end
end
