# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BedrockListBatchJobs200ResponseInvocationJobSummariesInner do
  @moduledoc """
  BedrockListBatchJobs200ResponseInvocationJobSummariesInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :jobArn,
    :jobName,
    :modelId,
    :status,
    :submitTime,
    :lastModifiedTime,
    :endTime,
    :message
  ]

  @type t :: %__MODULE__{
          :jobArn => String.t() | nil,
          :jobName => String.t() | nil,
          :modelId => String.t() | nil,
          :status => String.t() | nil,
          :submitTime => DateTime.t() | nil,
          :lastModifiedTime => DateTime.t() | nil,
          :endTime => DateTime.t() | nil,
          :message => String.t() | nil
        }

  def decode(value) do
    value
  end
end
