# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.BifrostCost do
  @moduledoc """
  Cost breakdown for the request
  """

  @derive JSON.Encoder
  defstruct [
    :input_tokens_cost,
    :output_tokens_cost,
    :reasoning_tokens_cost,
    :citation_tokens_cost,
    :search_queries_cost,
    :request_cost,
    :total_cost
  ]

  @type t :: %__MODULE__{
          :input_tokens_cost => number() | nil,
          :output_tokens_cost => number() | nil,
          :reasoning_tokens_cost => number() | nil,
          :citation_tokens_cost => number() | nil,
          :search_queries_cost => number() | nil,
          :request_cost => number() | nil,
          :total_cost => number() | nil
        }

  def decode(value) do
    value
  end
end
