# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.Budget do
  @moduledoc """
  Budget configuration
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :max_limit,
    :reset_duration,
    :calendar_aligned,
    :last_reset,
    :current_usage,
    :team_id,
    :virtual_key_id,
    :provider_config_id,
    :config_hash,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :max_limit => number(),
          :reset_duration => String.t(),
          :calendar_aligned => boolean() | nil,
          :last_reset => DateTime.t(),
          :current_usage => number(),
          :team_id => String.t() | nil,
          :virtual_key_id => String.t() | nil,
          :provider_config_id => integer() | nil,
          :config_hash => String.t() | nil,
          :created_at => DateTime.t(),
          :updated_at => DateTime.t()
        }

  def decode(value) do
    value
  end
end
