# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CancelBatch200ResponseRequestCounts do
  @moduledoc """
  CancelBatch200ResponseRequestCounts model.
  """

  @derive JSON.Encoder
  defstruct [
    :total,
    :completed,
    :failed,
    :succeeded,
    :expired,
    :canceled,
    :pending
  ]

  @type t :: %__MODULE__{
          :total => integer() | nil,
          :completed => integer() | nil,
          :failed => integer() | nil,
          :succeeded => integer() | nil,
          :expired => integer() | nil,
          :canceled => integer() | nil,
          :pending => integer() | nil
        }

  def decode(value) do
    value
  end
end
