# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ChatMessageContentOneOfInner do
  @moduledoc """
  ChatMessageContentOneOfInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :text,
    :refusal,
    :image_url,
    :input_audio,
    :file,
    :cache_control
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :text => String.t() | nil,
          :refusal => String.t() | nil,
          :image_url => ExBifrost.Model.ChatMessageContentOneOfInnerImageUrl.t() | nil,
          :input_audio => ExBifrost.Model.ChatMessageContentOneOfInnerInputAudio.t() | nil,
          :file => ExBifrost.Model.ChatMessageContentOneOfInnerFile.t() | nil,
          :cache_control => ExBifrost.Model.CacheControl.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:image_url, :struct, ExBifrost.Model.ChatMessageContentOneOfInnerImageUrl)
    |> Deserializer.deserialize(:input_audio, :struct, ExBifrost.Model.ChatMessageContentOneOfInnerInputAudio)
    |> Deserializer.deserialize(:file, :struct, ExBifrost.Model.ChatMessageContentOneOfInnerFile)
    |> Deserializer.deserialize(:cache_control, :struct, ExBifrost.Model.CacheControl)
  end
end
