# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ChatDefault do
  @moduledoc """
  Chat format - uses ChatAssistantMessageToolCall schema
  """

  @derive JSON.Encoder
  defstruct [
    :index,
    :type,
    :id,
    :function
  ]

  @type t :: %__MODULE__{
          :index => integer() | nil,
          :type => String.t() | nil,
          :id => String.t() | nil,
          :function => ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerDeltaToolCallsInnerFunction.t()
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :function,
      :struct,
      ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerDeltaToolCallsInnerFunction
    )
  end
end
