# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ChatMessageAnnotationsInnerUrlCitation do
  @moduledoc """
  ChatMessageAnnotationsInnerUrlCitation model.
  """

  @derive JSON.Encoder
  defstruct [
    :start_index,
    :end_index,
    :title,
    :url,
    :sources,
    :type
  ]

  @type t :: %__MODULE__{
          :start_index => integer() | nil,
          :end_index => integer() | nil,
          :title => String.t() | nil,
          :url => String.t() | nil,
          :sources => map() | nil,
          :type => String.t() | nil
        }

  def decode(value) do
    value
  end
end
