# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ChatCompletionRequestToolsInnerCustomFormatGrammar do
  @moduledoc """
  ChatCompletionRequestToolsInnerCustomFormatGrammar model.
  """

  @derive JSON.Encoder
  defstruct [
    :definition,
    :syntax
  ]

  @type t :: %__MODULE__{
          :definition => String.t(),
          :syntax => String.t()
        }

  def decode(value) do
    value
  end
end
