# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereChatV2200ResponseDeltaMessageContentOneOf do
  @moduledoc """
  CohereChatV2200ResponseDeltaMessageContentOneOf model.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :text,
    :thinking
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :text => String.t() | nil,
          :thinking => String.t() | nil
        }

  def decode(value) do
    value
  end
end
