# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereChatV2200ResponseDeltaMessageCitationsOneOfSourcesInner do
  @moduledoc """
  CohereChatV2200ResponseDeltaMessageCitationsOneOfSourcesInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :id,
    :tool_output,
    :document
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :id => String.t() | nil,
          :tool_output => map() | nil,
          :document => map() | nil
        }

  def decode(value) do
    value
  end
end
