# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereChatV2200ResponseDeltaMessage do
  @moduledoc """
  CohereChatV2200ResponseDeltaMessage model.
  """

  @derive JSON.Encoder
  defstruct [
    :role,
    :content,
    :tool_plan,
    :tool_calls,
    :citations
  ]

  @type t :: %__MODULE__{
          :role => String.t() | nil,
          :content => ExBifrost.Model.CohereChatV2200ResponseDeltaMessageContent.t() | nil,
          :tool_plan => String.t() | nil,
          :tool_calls => ExBifrost.Model.CohereChatV2200ResponseDeltaMessageToolCalls.t() | nil,
          :citations => ExBifrost.Model.CohereChatV2200ResponseDeltaMessageCitations.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:content, :struct, ExBifrost.Model.CohereChatV2200ResponseDeltaMessageContent)
    |> Deserializer.deserialize(:tool_calls, :struct, ExBifrost.Model.CohereChatV2200ResponseDeltaMessageToolCalls)
    |> Deserializer.deserialize(:citations, :struct, ExBifrost.Model.CohereChatV2200ResponseDeltaMessageCitations)
  end
end
