# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereError do
  @moduledoc """
  CohereError model.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :message,
    :code
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :message => String.t() | nil,
          :code => String.t() | nil
        }

  def decode(value) do
    value
  end
end
