# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereChatResponseMessageContentInnerImageUrl do
  @moduledoc """
  CohereChatResponseMessageContentInnerImageUrl model.
  """

  @derive JSON.Encoder
  defstruct [
    :url
  ]

  @type t :: %__MODULE__{
          :url => String.t() | nil
        }

  def decode(value) do
    value
  end
end
