# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereChatV2200ResponseDeltaUsage do
  @moduledoc """
  CohereChatV2200ResponseDeltaUsage model.
  """

  @derive JSON.Encoder
  defstruct [
    :billed_units,
    :tokens,
    :cached_tokens
  ]

  @type t :: %__MODULE__{
          :billed_units => ExBifrost.Model.CohereChatV2200ResponseDeltaUsageBilledUnits.t() | nil,
          :tokens => ExBifrost.Model.AnthropicCreateComplete200ResponseUsage.t() | nil,
          :cached_tokens => integer() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:billed_units, :struct, ExBifrost.Model.CohereChatV2200ResponseDeltaUsageBilledUnits)
    |> Deserializer.deserialize(:tokens, :struct, ExBifrost.Model.AnthropicCreateComplete200ResponseUsage)
  end
end
