# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereChatResponseMessage do
  @moduledoc """
  CohereChatResponseMessage model.
  """

  @derive JSON.Encoder
  defstruct [
    :role,
    :content,
    :tool_calls,
    :tool_plan
  ]

  @type t :: %__MODULE__{
          :role => String.t() | nil,
          :content => [ExBifrost.Model.CohereChatResponseMessageContentInner.t()] | nil,
          :tool_calls => [ExBifrost.Model.CohereChatV2200ResponseDeltaMessageToolCallsOneOf.t()] | nil,
          :tool_plan => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:content, :list, ExBifrost.Model.CohereChatResponseMessageContentInner)
    |> Deserializer.deserialize(:tool_calls, :list, ExBifrost.Model.CohereChatV2200ResponseDeltaMessageToolCallsOneOf)
  end
end
