# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereEmbeddingResponseImagesInner do
  @moduledoc """
  Image information in the response
  """

  @derive JSON.Encoder
  defstruct [
    :width,
    :height,
    :format,
    :bit_depth
  ]

  @type t :: %__MODULE__{
          :width => integer() | nil,
          :height => integer() | nil,
          :format => String.t() | nil,
          :bit_depth => integer() | nil
        }

  def decode(value) do
    value
  end
end
