# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereEmbeddingResponseMetaApiVersion do
  @moduledoc """
  API version information
  """

  @derive JSON.Encoder
  defstruct [
    :version,
    :is_deprecated,
    :is_experimental
  ]

  @type t :: %__MODULE__{
          :version => String.t() | nil,
          :is_deprecated => boolean() | nil,
          :is_experimental => boolean() | nil
        }

  def decode(value) do
    value
  end
end
