# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CohereChatResponse do
  @moduledoc """
  CohereChatResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :finish_reason,
    :message,
    :usage,
    :logprobs
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :finish_reason => String.t() | nil,
          :message => ExBifrost.Model.CohereChatResponseMessage.t() | nil,
          :usage => ExBifrost.Model.CohereChatV2200ResponseDeltaUsage.t() | nil,
          :logprobs => [ExBifrost.Model.CohereChatResponseLogprobsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:message, :struct, ExBifrost.Model.CohereChatResponseMessage)
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.CohereChatV2200ResponseDeltaUsage)
    |> Deserializer.deserialize(:logprobs, :list, ExBifrost.Model.CohereChatResponseLogprobsInner)
  end
end
