# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateSpeech200Response do
  @moduledoc """
  CreateSpeech200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :audio,
    :usage,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :audio => binary() | nil,
          :usage => ExBifrost.Model.CreateSpeech200ResponseUsage.t() | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.CreateSpeech200ResponseUsage)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
