# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerDeltaReasoningDetailsInner do
  @moduledoc """
  CreateChatCompletion200ResponseChoicesInnerDeltaReasoningDetailsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :index,
    :type,
    :summary,
    :text,
    :signature,
    :data
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :index => integer() | nil,
          :type => String.t() | nil,
          :summary => String.t() | nil,
          :text => String.t() | nil,
          :signature => String.t() | nil,
          :data => String.t() | nil
        }

  def decode(value) do
    value
  end
end
