# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateContainer200Response do
  @moduledoc """
  CreateContainer200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :object,
    :name,
    :created_at,
    :status,
    :expires_after,
    :last_active_at,
    :memory_limit,
    :metadata,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :object => String.t() | nil,
          :name => String.t() | nil,
          :created_at => integer() | nil,
          :status => String.t() | nil,
          :expires_after => ExBifrost.Model.ListContainers200ResponseDataInnerExpiresAfter.t() | nil,
          :last_active_at => integer() | nil,
          :memory_limit => String.t() | nil,
          :metadata => %{optional(String.t()) => String.t()} | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:expires_after, :struct, ExBifrost.Model.ListContainers200ResponseDataInnerExpiresAfter)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
