# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateContainerRequest do
  @moduledoc """
  CreateContainerRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :name,
    :expires_after,
    :file_ids,
    :memory_limit,
    :metadata
  ]

  @type t :: %__MODULE__{
          :provider => ExBifrost.Model.ModelProvider.t(),
          :name => String.t(),
          :expires_after => ExBifrost.Model.ListContainers200ResponseDataInnerExpiresAfter.t() | nil,
          :file_ids => [String.t()] | nil,
          :memory_limit => String.t() | nil,
          :metadata => %{optional(String.t()) => String.t()} | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:provider, :struct, ExBifrost.Model.ModelProvider)
    |> Deserializer.deserialize(:expires_after, :struct, ExBifrost.Model.ListContainers200ResponseDataInnerExpiresAfter)
  end
end
