# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreatePromptSession200Response do
  @moduledoc """
  CreatePromptSession200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :session
  ]

  @type t :: %__MODULE__{
          :session => ExBifrost.Model.ListPrompts200ResponsePromptsInnerSessionsInner.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:session, :struct, ExBifrost.Model.ListPrompts200ResponsePromptsInnerSessionsInner)
  end
end
