# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerLogProbsContentInner do
  @moduledoc """
  CreateChatCompletion200ResponseChoicesInnerLogProbsContentInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :bytes,
    :logprob,
    :token,
    :top_logprobs
  ]

  @type t :: %__MODULE__{
          :bytes => [integer()] | nil,
          :logprob => number() | nil,
          :token => String.t() | nil,
          :top_logprobs =>
            [ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerLogProbsContentInnerTopLogprobsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :top_logprobs,
      :list,
      ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerLogProbsContentInnerTopLogprobsInner
    )
  end
end
