# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerDeltaAudio do
  @moduledoc """
  CreateChatCompletion200ResponseChoicesInnerDeltaAudio model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :data,
    :expires_at,
    :transcript
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :data => String.t() | nil,
          :expires_at => integer() | nil,
          :transcript => String.t() | nil
        }

  def decode(value) do
    value
  end
end
