# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreatePluginRequest do
  @moduledoc """
  Create plugin request
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :enabled,
    :config,
    :path
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :enabled => boolean() | nil,
          :config => %{optional(String.t()) => any()} | nil,
          :path => String.t() | nil
        }

  def decode(value) do
    value
  end
end
