# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateContainerFile200Response do
  @moduledoc """
  Response from creating a file in a container
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :object,
    :container_id,
    :path,
    :bytes,
    :created_at,
    :source,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :object => String.t() | nil,
          :container_id => String.t() | nil,
          :path => String.t() | nil,
          :bytes => integer() | nil,
          :created_at => integer() | nil,
          :source => String.t() | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
