# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateContainerFileRequest1 do
  @moduledoc """
  Request to create a file in a container by referencing an existing file
  """

  @derive JSON.Encoder
  defstruct [
    :file_id,
    :file_path
  ]

  @type t :: %__MODULE__{
          :file_id => String.t(),
          :file_path => String.t() | nil
        }

  def decode(value) do
    value
  end
end
