# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateVirtualKeyRequestMcpConfigsInner do
  @moduledoc """
  CreateVirtualKeyRequestMcpConfigsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :mcp_client_name,
    :tools_to_execute
  ]

  @type t :: %__MODULE__{
          :mcp_client_name => String.t() | nil,
          :tools_to_execute => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
