# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateFolder200Response do
  @moduledoc """
  CreateFolder200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :folder
  ]

  @type t :: %__MODULE__{
          :folder => ExBifrost.Model.ListFolders200ResponseFoldersInner.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:folder, :struct, ExBifrost.Model.ListFolders200ResponseFoldersInner)
  end
end
