# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.CreateResponse200Response do
  @moduledoc """
  Streaming responses API response (SSE format)
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :sequence_number,
    :response,
    :output_index,
    :item,
    :content_index,
    :item_id,
    :part,
    :delta,
    :signature,
    :logprobs,
    :text,
    :refusal,
    :arguments,
    :partial_image_b64,
    :partial_image_index,
    :annotation,
    :annotation_index,
    :code,
    :message,
    :param,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :sequence_number => integer() | nil,
          :response => ExBifrost.Model.ResponsesResponse.t() | nil,
          :output_index => integer() | nil,
          :item => ExBifrost.Model.CreateResponse200ResponseItem.t() | nil,
          :content_index => integer() | nil,
          :item_id => String.t() | nil,
          :part => ExBifrost.Model.CreateResponse200ResponseItemContentOneOfInner.t() | nil,
          :delta => String.t() | nil,
          :signature => String.t() | nil,
          :logprobs => [ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerLogProbsContentInner.t()] | nil,
          :text => String.t() | nil,
          :refusal => String.t() | nil,
          :arguments => String.t() | nil,
          :partial_image_b64 => String.t() | nil,
          :partial_image_index => integer() | nil,
          :annotation => ExBifrost.Model.CreateResponse200ResponseItemContentOneOfInnerAnnotationsInner.t() | nil,
          :annotation_index => integer() | nil,
          :code => String.t() | nil,
          :message => String.t() | nil,
          :param => String.t() | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:response, :struct, ExBifrost.Model.ResponsesResponse)
    |> Deserializer.deserialize(:item, :struct, ExBifrost.Model.CreateResponse200ResponseItem)
    |> Deserializer.deserialize(:part, :struct, ExBifrost.Model.CreateResponse200ResponseItemContentOneOfInner)
    |> Deserializer.deserialize(
      :logprobs,
      :list,
      ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerLogProbsContentInner
    )
    |> Deserializer.deserialize(
      :annotation,
      :struct,
      ExBifrost.Model.CreateResponse200ResponseItemContentOneOfInnerAnnotationsInner
    )
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
