# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.EmbeddingRequest do
  @moduledoc """
  EmbeddingRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :input,
    :fallbacks,
    :encoding_format,
    :dimensions
  ]

  @type t :: %__MODULE__{
          :model => String.t(),
          :input => ExBifrost.Model.EmbeddingRequestInput.t(),
          :fallbacks => [String.t()] | nil,
          :encoding_format => String.t() | nil,
          :dimensions => integer() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:input, :struct, ExBifrost.Model.EmbeddingRequestInput)
  end
end
