# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.EmbeddingResponseDataInner do
  @moduledoc """
  EmbeddingResponseDataInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :index,
    :object,
    :embedding
  ]

  @type t :: %__MODULE__{
          :index => integer() | nil,
          :object => String.t() | nil,
          :embedding => ExBifrost.Model.EmbeddingResponseDataInnerEmbedding.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:embedding, :struct, ExBifrost.Model.EmbeddingResponseDataInnerEmbedding)
  end
end
