# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.EmbeddingResponse do
  @moduledoc """
  EmbeddingResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :model,
    :object,
    :usage,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :data => [ExBifrost.Model.EmbeddingResponseDataInner.t()] | nil,
          :model => String.t() | nil,
          :object => String.t() | nil,
          :usage => ExBifrost.Model.BifrostLlmUsage.t() | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:data, :list, ExBifrost.Model.EmbeddingResponseDataInner)
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.BifrostLlmUsage)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
