# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.FileListResponseDataInner do
  @moduledoc """
  FileListResponseDataInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :object,
    :bytes,
    :created_at,
    :filename,
    :purpose,
    :status,
    :status_details,
    :expires_at
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :object => String.t() | nil,
          :bytes => integer() | nil,
          :created_at => integer() | nil,
          :filename => String.t() | nil,
          :purpose => String.t() | nil,
          :status => String.t() | nil,
          :status_details => String.t() | nil,
          :expires_at => integer() | nil
        }

  def decode(value) do
    value
  end
end
