# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiContent do
  @moduledoc """
  GeminiContent model.
  """

  @derive JSON.Encoder
  defstruct [
    :role,
    :parts
  ]

  @type t :: %__MODULE__{
          :role => String.t() | nil,
          :parts => [ExBifrost.Model.GeminiPart.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:parts, :list, ExBifrost.Model.GeminiPart)
  end
end
