# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiEmbeddingResponseEmbeddingsInner do
  @moduledoc """
  GeminiEmbeddingResponseEmbeddingsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :values,
    :statistics
  ]

  @type t :: %__MODULE__{
          :values => [number()] | nil,
          :statistics => ExBifrost.Model.GeminiEmbeddingResponseEmbeddingsInnerStatistics.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:statistics, :struct, ExBifrost.Model.GeminiEmbeddingResponseEmbeddingsInnerStatistics)
  end
end
