# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationResponseCandidatesInner do
  @moduledoc """
  GeminiGenerationResponseCandidatesInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :content,
    :finishReason,
    :finishMessage,
    :tokenCount,
    :safetyRatings,
    :citationMetadata,
    :index,
    :groundingMetadata,
    :urlContextMetadata,
    :avgLogprobs,
    :logprobsResult
  ]

  @type t :: %__MODULE__{
          :content => ExBifrost.Model.GeminiContent.t() | nil,
          :finishReason => String.t() | nil,
          :finishMessage => String.t() | nil,
          :tokenCount => integer() | nil,
          :safetyRatings => [ExBifrost.Model.GeminiGenerationResponseCandidatesInnerSafetyRatingsInner.t()] | nil,
          :citationMetadata => map() | nil,
          :index => integer() | nil,
          :groundingMetadata => map() | nil,
          :urlContextMetadata => ExBifrost.Model.GeminiGenerationResponseCandidatesInnerUrlContextMetadata.t() | nil,
          :avgLogprobs => number() | nil,
          :logprobsResult => ExBifrost.Model.GeminiGenerationResponseCandidatesInnerLogprobsResult.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:content, :struct, ExBifrost.Model.GeminiContent)
    |> Deserializer.deserialize(
      :safetyRatings,
      :list,
      ExBifrost.Model.GeminiGenerationResponseCandidatesInnerSafetyRatingsInner
    )
    |> Deserializer.deserialize(
      :urlContextMetadata,
      :struct,
      ExBifrost.Model.GeminiGenerationResponseCandidatesInnerUrlContextMetadata
    )
    |> Deserializer.deserialize(
      :logprobsResult,
      :struct,
      ExBifrost.Model.GeminiGenerationResponseCandidatesInnerLogprobsResult
    )
  end
end
