# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiError do
  @moduledoc """
  GeminiError model.
  """

  @derive JSON.Encoder
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
          :error => ExBifrost.Model.GeminiErrorError.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:error, :struct, ExBifrost.Model.GeminiErrorError)
  end
end
