# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexRagStore do
  @moduledoc """
  GeminiGenerationRequestToolsInnerRetrievalVertexRagStore model.
  """

  @derive JSON.Encoder
  defstruct [
    :ragCorpora,
    :ragResources,
    :ragRetrievalConfig,
    :similarityTopK,
    :storeContext,
    :vectorDistanceThreshold
  ]

  @type t :: %__MODULE__{
          :ragCorpora => [String.t()] | nil,
          :ragResources =>
            [ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexRagStoreRagResourcesInner.t()] | nil,
          :ragRetrievalConfig =>
            ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexRagStoreRagRetrievalConfig.t() | nil,
          :similarityTopK => integer() | nil,
          :storeContext => boolean() | nil,
          :vectorDistanceThreshold => number() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :ragResources,
      :list,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexRagStoreRagResourcesInner
    )
    |> Deserializer.deserialize(
      :ragRetrievalConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexRagStoreRagRetrievalConfig
    )
  end
end
