# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestToolConfigRetrievalConfig do
  @moduledoc """
  GeminiGenerationRequestToolConfigRetrievalConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :latLng,
    :languageCode
  ]

  @type t :: %__MODULE__{
          :latLng => ExBifrost.Model.GeminiGenerationRequestToolConfigRetrievalConfigLatLng.t() | nil,
          :languageCode => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :latLng,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolConfigRetrievalConfigLatLng
    )
  end
end
