# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestSafetySettingsInner do
  @moduledoc """
  GeminiGenerationRequestSafetySettingsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :category,
    :threshold,
    :method
  ]

  @type t :: %__MODULE__{
          :category => String.t() | nil,
          :threshold => String.t() | nil,
          :method => String.t() | nil
        }

  def decode(value) do
    value
  end
end
