# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationResponseUsageMetadata do
  @moduledoc """
  GeminiGenerationResponseUsageMetadata model.
  """

  @derive JSON.Encoder
  defstruct [
    :promptTokenCount,
    :candidatesTokenCount,
    :totalTokenCount,
    :cachedContentTokenCount,
    :thoughtsTokenCount,
    :toolUsePromptTokenCount,
    :trafficType,
    :cacheTokensDetails,
    :candidatesTokensDetails,
    :promptTokensDetails,
    :toolUsePromptTokensDetails
  ]

  @type t :: %__MODULE__{
          :promptTokenCount => integer() | nil,
          :candidatesTokenCount => integer() | nil,
          :totalTokenCount => integer() | nil,
          :cachedContentTokenCount => integer() | nil,
          :thoughtsTokenCount => integer() | nil,
          :toolUsePromptTokenCount => integer() | nil,
          :trafficType => String.t() | nil,
          :cacheTokensDetails => [ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner.t()] | nil,
          :candidatesTokensDetails => [ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner.t()] | nil,
          :promptTokensDetails => [ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner.t()] | nil,
          :toolUsePromptTokensDetails =>
            [ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :cacheTokensDetails,
      :list,
      ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner
    )
    |> Deserializer.deserialize(
      :candidatesTokensDetails,
      :list,
      ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner
    )
    |> Deserializer.deserialize(
      :promptTokensDetails,
      :list,
      ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner
    )
    |> Deserializer.deserialize(
      :toolUsePromptTokensDetails,
      :list,
      ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner
    )
  end
end
