# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner do
  @moduledoc """
  GeminiCountTokens200ResponsePromptTokensDetailsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :modality,
    :tokenCount
  ]

  @type t :: %__MODULE__{
          :modality => String.t() | nil,
          :tokenCount => integer() | nil
        }

  def decode(value) do
    value
  end
end
