# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfig do
  @moduledoc """
  GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :authType,
    :apiKeyConfig,
    :googleServiceAccountConfig,
    :httpBasicAuthConfig,
    :oauthConfig,
    :oidcConfig
  ]

  @type t :: %__MODULE__{
          :authType => String.t() | nil,
          :apiKeyConfig =>
            ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigApiKeyConfig.t() | nil,
          :googleServiceAccountConfig =>
            ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigGoogleServiceAccountConfig.t()
            | nil,
          :httpBasicAuthConfig =>
            ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigHttpBasicAuthConfig.t() | nil,
          :oauthConfig =>
            ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigOauthConfig.t() | nil,
          :oidcConfig =>
            ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigOidcConfig.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :apiKeyConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigApiKeyConfig
    )
    |> Deserializer.deserialize(
      :googleServiceAccountConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigGoogleServiceAccountConfig
    )
    |> Deserializer.deserialize(
      :httpBasicAuthConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigHttpBasicAuthConfig
    )
    |> Deserializer.deserialize(
      :oauthConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigOauthConfig
    )
    |> Deserializer.deserialize(
      :oidcConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApiAuthConfigOidcConfig
    )
  end
end
