# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiErrorErrorDetailsInner do
  @moduledoc """
  GeminiErrorErrorDetailsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :"@type",
    :fieldViolations
  ]

  @type t :: %__MODULE__{
          :"@type" => String.t() | nil,
          :fieldViolations => [ExBifrost.Model.UpdateTeamRequest.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:fieldViolations, :list, ExBifrost.Model.UpdateTeamRequest)
  end
end
