# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiUploadFile200ResponseFile do
  @moduledoc """
  GeminiUploadFile200ResponseFile model.
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :displayName,
    :mimeType,
    :sizeBytes,
    :createTime,
    :updateTime,
    :expirationTime,
    :sha256Hash,
    :uri,
    :state,
    :error,
    :videoMetadata
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :displayName => String.t() | nil,
          :mimeType => String.t() | nil,
          :sizeBytes => String.t() | nil,
          :createTime => DateTime.t() | nil,
          :updateTime => DateTime.t() | nil,
          :expirationTime => DateTime.t() | nil,
          :sha256Hash => String.t() | nil,
          :uri => String.t() | nil,
          :state => String.t() | nil,
          :error => ExBifrost.Model.GeminiUploadFile200ResponseFileError.t() | nil,
          :videoMetadata => ExBifrost.Model.GeminiUploadFile200ResponseFileVideoMetadata.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:error, :struct, ExBifrost.Model.GeminiUploadFile200ResponseFileError)
    |> Deserializer.deserialize(:videoMetadata, :struct, ExBifrost.Model.GeminiUploadFile200ResponseFileVideoMetadata)
  end
end
