# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrieval do
  @moduledoc """
  GeminiGenerationRequestToolsInnerRetrieval model.
  """

  @derive JSON.Encoder
  defstruct [
    :disableAttribution,
    :externalApi,
    :vertexAiSearch,
    :vertexRagStore
  ]

  @type t :: %__MODULE__{
          :disableAttribution => boolean() | nil,
          :externalApi => ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApi.t() | nil,
          :vertexAiSearch => ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexAiSearch.t() | nil,
          :vertexRagStore => ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexRagStore.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :externalApi,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalExternalApi
    )
    |> Deserializer.deserialize(
      :vertexAiSearch,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexAiSearch
    )
    |> Deserializer.deserialize(
      :vertexRagStore,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexRagStore
    )
  end
end
