# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiErrorError do
  @moduledoc """
  GeminiErrorError model.
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :message,
    :status,
    :details
  ]

  @type t :: %__MODULE__{
          :code => integer() | nil,
          :message => String.t() | nil,
          :status => String.t() | nil,
          :details => [ExBifrost.Model.GeminiErrorErrorDetailsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:details, :list, ExBifrost.Model.GeminiErrorErrorDetailsInner)
  end
end
