# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiCountTokens200Response do
  @moduledoc """
  GeminiCountTokens200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :totalTokens,
    :cachedContentTokenCount,
    :promptTokensDetails,
    :cacheTokensDetails
  ]

  @type t :: %__MODULE__{
          :totalTokens => integer() | nil,
          :cachedContentTokenCount => integer() | nil,
          :promptTokensDetails => [ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner.t()] | nil,
          :cacheTokensDetails => [ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :promptTokensDetails,
      :list,
      ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner
    )
    |> Deserializer.deserialize(
      :cacheTokensDetails,
      :list,
      ExBifrost.Model.GeminiCountTokens200ResponsePromptTokensDetailsInner
    )
  end
end
