# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiCreateCachedContentRequest do
  @moduledoc """
  GeminiCreateCachedContentRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :displayName,
    :systemInstruction,
    :contents,
    :tools,
    :toolConfig,
    :ttl,
    :expireTime
  ]

  @type t :: %__MODULE__{
          :model => String.t(),
          :displayName => String.t() | nil,
          :systemInstruction => %{optional(String.t()) => any()} | nil,
          :contents => [any()] | nil,
          :tools => [any()] | nil,
          :toolConfig => any() | nil,
          :ttl => String.t() | nil,
          :expireTime => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
