# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestToolsInnerGoogleSearchRetrieval do
  @moduledoc """
  GeminiGenerationRequestToolsInnerGoogleSearchRetrieval model.
  """

  @derive JSON.Encoder
  defstruct [
    :dynamicRetrievalConfig
  ]

  @type t :: %__MODULE__{
          :dynamicRetrievalConfig =>
            ExBifrost.Model.GeminiGenerationRequestToolsInnerGoogleSearchRetrievalDynamicRetrievalConfig.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :dynamicRetrievalConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerGoogleSearchRetrievalDynamicRetrievalConfig
    )
  end
end
