# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestToolsInnerGoogleSearchRetrievalDynamicRetrievalConfig do
  @moduledoc """
  GeminiGenerationRequestToolsInnerGoogleSearchRetrievalDynamicRetrievalConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :mode,
    :dynamicThreshold
  ]

  @type t :: %__MODULE__{
          :mode => String.t() | nil,
          :dynamicThreshold => number() | nil
        }

  def decode(value) do
    value
  end
end
