# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiUploadFile200Response do
  @moduledoc """
  GeminiUploadFile200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :file
  ]

  @type t :: %__MODULE__{
          :file => ExBifrost.Model.GeminiUploadFile200ResponseFile.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:file, :struct, ExBifrost.Model.GeminiUploadFile200ResponseFile)
  end
end
