# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexAiSearch do
  @moduledoc """
  GeminiGenerationRequestToolsInnerRetrievalVertexAiSearch model.
  """

  @derive JSON.Encoder
  defstruct [
    :datastore,
    :engine,
    :filter,
    :maxResults,
    :dataStoreSpecs
  ]

  @type t :: %__MODULE__{
          :datastore => String.t() | nil,
          :engine => String.t() | nil,
          :filter => String.t() | nil,
          :maxResults => integer() | nil,
          :dataStoreSpecs =>
            [ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexAiSearchDataStoreSpecsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :dataStoreSpecs,
      :list,
      ExBifrost.Model.GeminiGenerationRequestToolsInnerRetrievalVertexAiSearchDataStoreSpecsInner
    )
  end
end
