# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiPart do
  @moduledoc """
  GeminiPart model.
  """

  @derive JSON.Encoder
  defstruct [
    :text,
    :thought,
    :thoughtSignature,
    :inlineData,
    :fileData,
    :functionCall,
    :functionResponse,
    :executableCode,
    :codeExecutionResult,
    :videoMetadata
  ]

  @type t :: %__MODULE__{
          :text => String.t() | nil,
          :thought => boolean() | nil,
          :thoughtSignature => binary() | nil,
          :inlineData => ExBifrost.Model.GeminiPartInlineData.t() | nil,
          :fileData => ExBifrost.Model.GeminiPartFileData.t() | nil,
          :functionCall => ExBifrost.Model.GeminiPartFunctionCall.t() | nil,
          :functionResponse => ExBifrost.Model.GeminiPartFunctionResponse.t() | nil,
          :executableCode => ExBifrost.Model.GeminiPartExecutableCode.t() | nil,
          :codeExecutionResult => ExBifrost.Model.GeminiPartCodeExecutionResult.t() | nil,
          :videoMetadata => ExBifrost.Model.GeminiPartVideoMetadata.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:inlineData, :struct, ExBifrost.Model.GeminiPartInlineData)
    |> Deserializer.deserialize(:fileData, :struct, ExBifrost.Model.GeminiPartFileData)
    |> Deserializer.deserialize(:functionCall, :struct, ExBifrost.Model.GeminiPartFunctionCall)
    |> Deserializer.deserialize(:functionResponse, :struct, ExBifrost.Model.GeminiPartFunctionResponse)
    |> Deserializer.deserialize(:executableCode, :struct, ExBifrost.Model.GeminiPartExecutableCode)
    |> Deserializer.deserialize(:codeExecutionResult, :struct, ExBifrost.Model.GeminiPartCodeExecutionResult)
    |> Deserializer.deserialize(:videoMetadata, :struct, ExBifrost.Model.GeminiPartVideoMetadata)
  end
end
