# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiGenerationRequestToolConfig do
  @moduledoc """
  GeminiGenerationRequestToolConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :functionCallingConfig,
    :retrievalConfig
  ]

  @type t :: %__MODULE__{
          :functionCallingConfig => ExBifrost.Model.GeminiGenerationRequestToolConfigFunctionCallingConfig.t() | nil,
          :retrievalConfig => ExBifrost.Model.GeminiGenerationRequestToolConfigRetrievalConfig.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :functionCallingConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolConfigFunctionCallingConfig
    )
    |> Deserializer.deserialize(
      :retrievalConfig,
      :struct,
      ExBifrost.Model.GeminiGenerationRequestToolConfigRetrievalConfig
    )
  end
end
