# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GeminiPartVideoMetadata do
  @moduledoc """
  GeminiPartVideoMetadata model.
  """

  @derive JSON.Encoder
  defstruct [
    :fps,
    :startOffset,
    :endOffset
  ]

  @type t :: %__MODULE__{
          :fps => number() | nil,
          :startOffset => String.t() | nil,
          :endOffset => String.t() | nil
        }

  def decode(value) do
    value
  end
end
