# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetTeamMembers200Response do
  @moduledoc """
  GetTeamMembers200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :members
  ]

  @type t :: %__MODULE__{
          :members => [ExBifrost.Model.GetTeamMembers200ResponseMembersInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:members, :list, ExBifrost.Model.GetTeamMembers200ResponseMembersInner)
  end
end
