# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetLogsTokenHistogram200Response do
  @moduledoc """
  Time-bucketed token usage histogram
  """

  @derive JSON.Encoder
  defstruct [
    :buckets,
    :bucket_size_seconds
  ]

  @type t :: %__MODULE__{
          :buckets => [ExBifrost.Model.GetLogsTokenHistogram200ResponseBucketsInner.t()] | nil,
          :bucket_size_seconds => integer() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:buckets, :list, ExBifrost.Model.GetLogsTokenHistogram200ResponseBucketsInner)
  end
end
