# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetDashboard200Response do
  @moduledoc """
  Consolidated payload containing every metric shown on the workspace dashboard. Each section mirrors the response of its dedicated endpoint, so consumers can integrate a single call instead of orchestrating many. 
  """

  @derive JSON.Encoder
  defstruct [
    :meta,
    :overview,
    :provider_usage,
    :model_rankings,
    :dimension_rankings,
    :mcp
  ]

  @type t :: %__MODULE__{
          :meta => ExBifrost.Model.GetDashboard200ResponseMeta.t() | nil,
          :overview => ExBifrost.Model.GetDashboard200ResponseOverview.t() | nil,
          :provider_usage => ExBifrost.Model.GetDashboard200ResponseProviderUsage.t() | nil,
          :model_rankings => ExBifrost.Model.GetDashboard200ResponseModelRankings.t() | nil,
          :dimension_rankings =>
            %{optional(String.t()) => ExBifrost.Model.GetDashboard200ResponseDimensionRankingsValue.t()} | nil,
          :mcp => ExBifrost.Model.GetDashboard200ResponseMcp.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:meta, :struct, ExBifrost.Model.GetDashboard200ResponseMeta)
    |> Deserializer.deserialize(:overview, :struct, ExBifrost.Model.GetDashboard200ResponseOverview)
    |> Deserializer.deserialize(:provider_usage, :struct, ExBifrost.Model.GetDashboard200ResponseProviderUsage)
    |> Deserializer.deserialize(:model_rankings, :struct, ExBifrost.Model.GetDashboard200ResponseModelRankings)
    |> Deserializer.deserialize(
      :dimension_rankings,
      :map,
      ExBifrost.Model.GetDashboard200ResponseDimensionRankingsValue
    )
    |> Deserializer.deserialize(:mcp, :struct, ExBifrost.Model.GetDashboard200ResponseMcp)
  end
end
