# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetMcpLogById200Response do
  @moduledoc """
  MCP tool execution log entry
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :llm_request_id,
    :timestamp,
    :tool_name,
    :server_label,
    :virtual_key_id,
    :virtual_key_name,
    :arguments,
    :result,
    :error_details,
    :latency,
    :cost,
    :status,
    :metadata,
    :created_at,
    :virtual_key
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :llm_request_id => String.t() | nil,
          :timestamp => DateTime.t() | nil,
          :tool_name => String.t() | nil,
          :server_label => String.t() | nil,
          :virtual_key_id => String.t() | nil,
          :virtual_key_name => String.t() | nil,
          :arguments => %{optional(String.t()) => any()} | nil,
          :result => %{optional(String.t()) => any()} | nil,
          :error_details => ExBifrost.Model.BifrostError.t() | nil,
          :latency => number() | nil,
          :cost => number() | nil,
          :status => String.t() | nil,
          :metadata => %{optional(String.t()) => any()} | nil,
          :created_at => DateTime.t() | nil,
          :virtual_key => %{optional(String.t()) => any()} | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:error_details, :struct, ExBifrost.Model.BifrostError)
  end
end
