# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetModelConfig200Response do
  @moduledoc """
  GetModelConfig200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :model_config
  ]

  @type t :: %__MODULE__{
          :model_config => ExBifrost.Model.ModelConfig.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:model_config, :struct, ExBifrost.Model.ModelConfig)
  end
end
