# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetConfigResponseClientConfigMcpExternalClientUrlOneOf do
  @moduledoc """
  GetConfigResponseClientConfigMcpExternalClientUrlOneOf model.
  """

  @derive JSON.Encoder
  defstruct [
    :value,
    :env_var,
    :from_env
  ]

  @type t :: %__MODULE__{
          :value => String.t() | nil,
          :env_var => String.t() | nil,
          :from_env => boolean() | nil
        }

  def decode(value) do
    value
  end
end
