# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetCircuitBreakerState200ResponseCircuitsValue do
  @moduledoc """
  Runtime state of a single circuit (main circuit or per-key sub-circuit).
  """

  @derive JSON.Encoder
  defstruct [
    :status,
    :opened_at,
    :cooldown,
    :expires_at
  ]

  @type t :: %__MODULE__{
          :status => String.t() | nil,
          :opened_at => DateTime.t() | nil,
          :cooldown => integer() | nil,
          :expires_at => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
