# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetMcpLogsFilterData200Response do
  @moduledoc """
  Available MCP log filter data
  """

  @derive JSON.Encoder
  defstruct [
    :tool_names,
    :server_labels,
    :virtual_keys
  ]

  @type t :: %__MODULE__{
          :tool_names => [String.t()] | nil,
          :server_labels => [String.t()] | nil,
          :virtual_keys => [ExBifrost.Model.AddUserAccessProfileVirtualKey200ResponseVirtualKey.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :virtual_keys,
      :list,
      ExBifrost.Model.AddUserAccessProfileVirtualKey200ResponseVirtualKey
    )
  end
end
