# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetModelRankings200Response do
  @moduledoc """
  Models ranked by usage with trend comparison
  """

  @derive JSON.Encoder
  defstruct [
    :rankings
  ]

  @type t :: %__MODULE__{
          :rankings => [ExBifrost.Model.GetModelRankings200ResponseRankingsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:rankings, :list, ExBifrost.Model.GetModelRankings200ResponseRankingsInner)
  end
end
