# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetConfigResponse do
  @moduledoc """
  Configuration response
  """

  @derive JSON.Encoder
  defstruct [
    :client_config,
    :framework_config,
    :auth_config,
    :is_db_connected,
    :is_cache_connected,
    :is_logs_connected,
    :proxy_config,
    :restart_required
  ]

  @type t :: %__MODULE__{
          :client_config => ExBifrost.Model.GetConfigResponseClientConfig.t() | nil,
          :framework_config => ExBifrost.Model.GetConfigResponseFrameworkConfig.t() | nil,
          :auth_config => ExBifrost.Model.GetConfigResponseAuthConfig.t() | nil,
          :is_db_connected => boolean() | nil,
          :is_cache_connected => boolean() | nil,
          :is_logs_connected => boolean() | nil,
          :proxy_config => ExBifrost.Model.GetProxyConfig200Response.t() | nil,
          :restart_required => ExBifrost.Model.GetConfigResponseRestartRequired.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:client_config, :struct, ExBifrost.Model.GetConfigResponseClientConfig)
    |> Deserializer.deserialize(:framework_config, :struct, ExBifrost.Model.GetConfigResponseFrameworkConfig)
    |> Deserializer.deserialize(:auth_config, :struct, ExBifrost.Model.GetConfigResponseAuthConfig)
    |> Deserializer.deserialize(:proxy_config, :struct, ExBifrost.Model.GetProxyConfig200Response)
    |> Deserializer.deserialize(:restart_required, :struct, ExBifrost.Model.GetConfigResponseRestartRequired)
  end
end
