# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetLogsDimensionCostHistogram200ResponseBucketsInner do
  @moduledoc """
  Time-bucketed cost data grouped by an arbitrary dimension
  """

  @derive JSON.Encoder
  defstruct [
    :timestamp,
    :total_cost,
    :by_dimension
  ]

  @type t :: %__MODULE__{
          :timestamp => DateTime.t() | nil,
          :total_cost => number() | nil,
          :by_dimension => %{optional(String.t()) => number()} | nil
        }

  def decode(value) do
    value
  end
end
