# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetCurrentUserPermissions200Response do
  @moduledoc """
  GetCurrentUserPermissions200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :permissions
  ]

  @type t :: %__MODULE__{
          :permissions => %{optional(String.t()) => %{optional(String.t()) => boolean()}} | nil
        }

  def decode(value) do
    value
  end
end
