# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetLogsModelHistogram200ResponseBucketsInnerByModelValue do
  @moduledoc """
  Usage statistics for a single model
  """

  @derive JSON.Encoder
  defstruct [
    :total,
    :success,
    :error
  ]

  @type t :: %__MODULE__{
          :total => integer() | nil,
          :success => integer() | nil,
          :error => integer() | nil
        }

  def decode(value) do
    value
  end
end
