# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetLogsDimensionLatencyHistogram200Response do
  @moduledoc """
  Dimension-grouped latency histogram result
  """

  @derive JSON.Encoder
  defstruct [
    :buckets,
    :bucket_size_seconds,
    :dimension,
    :dimension_values
  ]

  @type t :: %__MODULE__{
          :buckets => [ExBifrost.Model.GetLogsDimensionLatencyHistogram200ResponseBucketsInner.t()] | nil,
          :bucket_size_seconds => integer() | nil,
          :dimension => String.t() | nil,
          :dimension_values => [String.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :buckets,
      :list,
      ExBifrost.Model.GetLogsDimensionLatencyHistogram200ResponseBucketsInner
    )
  end
end
