# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetComplexityAnalyzerConfig200ResponseTierBoundaries do
  @moduledoc """
  Score thresholds for complexity tier classification. All values must satisfy 0 < simple_medium < medium_complex < complex_reasoning < 1.
  """

  @derive JSON.Encoder
  defstruct [
    :simple_medium,
    :medium_complex,
    :complex_reasoning
  ]

  @type t :: %__MODULE__{
          :simple_medium => number(),
          :medium_complex => number(),
          :complex_reasoning => number()
        }

  def decode(value) do
    value
  end
end
