# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetMcpClients200Response do
  @moduledoc """
  Paginated list of MCP clients.
  """

  @derive JSON.Encoder
  defstruct [
    :clients,
    :count,
    :total_count,
    :limit,
    :offset
  ]

  @type t :: %__MODULE__{
          :clients => [ExBifrost.Model.McpClient.t()],
          :count => integer(),
          :total_count => integer(),
          :limit => integer(),
          :offset => integer()
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:clients, :list, ExBifrost.Model.McpClient)
  end
end
