# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetConfigResponseRestartRequired do
  @moduledoc """
  Restart required configuration
  """

  @derive JSON.Encoder
  defstruct [
    :required,
    :reason
  ]

  @type t :: %__MODULE__{
          :required => boolean() | nil,
          :reason => String.t() | nil
        }

  def decode(value) do
    value
  end
end
