# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetDashboard200ResponseMcpTopTools do
  @moduledoc """
  Top MCP tools by call count (limit 10)
  """

  @derive JSON.Encoder
  defstruct [
    :tools
  ]

  @type t :: %__MODULE__{
          :tools => [ExBifrost.Model.GetDashboard200ResponseMcpTopToolsToolsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:tools, :list, ExBifrost.Model.GetDashboard200ResponseMcpTopToolsToolsInner)
  end
end
