# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetMcpLogsStats200Response do
  @moduledoc """
  MCP tool log statistics
  """

  @derive JSON.Encoder
  defstruct [
    :total_executions,
    :success_rate,
    :average_latency,
    :total_cost
  ]

  @type t :: %__MODULE__{
          :total_executions => integer() | nil,
          :success_rate => number() | nil,
          :average_latency => number() | nil,
          :total_cost => number() | nil
        }

  def decode(value) do
    value
  end
end
