# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetMcpLogs200Response do
  @moduledoc """
  Search MCP logs response
  """

  @derive JSON.Encoder
  defstruct [
    :logs,
    :pagination,
    :has_logs
  ]

  @type t :: %__MODULE__{
          :logs => [ExBifrost.Model.GetMcpLogs200ResponseLogsInner.t()] | nil,
          :pagination => ExBifrost.Model.GetMcpLogs200ResponsePagination.t() | nil,
          :has_logs => boolean() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:logs, :list, ExBifrost.Model.GetMcpLogs200ResponseLogsInner)
    |> Deserializer.deserialize(:pagination, :struct, ExBifrost.Model.GetMcpLogs200ResponsePagination)
  end
end
