# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetLogsDimensionTokenHistogram200ResponseBucketsInner do
  @moduledoc """
  Time-bucketed token usage grouped by an arbitrary dimension
  """

  @derive JSON.Encoder
  defstruct [
    :timestamp,
    :by_dimension
  ]

  @type t :: %__MODULE__{
          :timestamp => DateTime.t() | nil,
          :by_dimension =>
            %{
              optional(String.t()) =>
                ExBifrost.Model.GetLogsProviderTokenHistogram200ResponseBucketsInnerByProviderValue.t()
            }
            | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :by_dimension,
      :map,
      ExBifrost.Model.GetLogsProviderTokenHistogram200ResponseBucketsInnerByProviderValue
    )
  end
end
