# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetUserVirtualKeysByEmail200Response do
  @moduledoc """
  GetUserVirtualKeysByEmail200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :user_id,
    :email,
    :virtual_keys
  ]

  @type t :: %__MODULE__{
          :user_id => String.t() | nil,
          :email => String.t() | nil,
          :virtual_keys => [ExBifrost.Model.GetUserVirtualKeysByEmail200ResponseVirtualKeysInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :virtual_keys,
      :list,
      ExBifrost.Model.GetUserVirtualKeysByEmail200ResponseVirtualKeysInner
    )
  end
end
