# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.GetConfigResponseFrameworkConfig do
  @moduledoc """
  Framework configuration
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :pricing_url,
    :pricing_sync_interval
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :pricing_url => String.t() | nil,
          :pricing_sync_interval => integer() | nil
        }

  def decode(value) do
    value
  end
end
