# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ImageGeneration200ResponseUsage do
  @moduledoc """
  ImageGeneration200ResponseUsage model.
  """

  @derive JSON.Encoder
  defstruct [
    :input_tokens,
    :input_tokens_details,
    :total_tokens,
    :output_tokens,
    :output_tokens_details
  ]

  @type t :: %__MODULE__{
          :input_tokens => integer() | nil,
          :input_tokens_details => ExBifrost.Model.ImageGeneration200ResponseUsageInputTokensDetails.t() | nil,
          :total_tokens => integer() | nil,
          :output_tokens => integer() | nil,
          :output_tokens_details => ExBifrost.Model.ImageGeneration200ResponseUsageInputTokensDetails.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :input_tokens_details,
      :struct,
      ExBifrost.Model.ImageGeneration200ResponseUsageInputTokensDetails
    )
    |> Deserializer.deserialize(
      :output_tokens_details,
      :struct,
      ExBifrost.Model.ImageGeneration200ResponseUsageInputTokensDetails
    )
  end
end
