# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ImageGenerationRequest do
  @moduledoc """
  ImageGenerationRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :prompt,
    :n,
    :size,
    :quality,
    :style,
    :response_format,
    :background,
    :moderation,
    :partial_images,
    :output_compression,
    :output_format,
    :user,
    :seed,
    :negative_prompt,
    :num_inference_steps,
    :stream,
    :fallbacks
  ]

  @type t :: %__MODULE__{
          :model => String.t(),
          :prompt => String.t(),
          :n => integer() | nil,
          :size => String.t() | nil,
          :quality => String.t() | nil,
          :style => String.t() | nil,
          :response_format => String.t() | nil,
          :background => String.t() | nil,
          :moderation => String.t() | nil,
          :partial_images => integer() | nil,
          :output_compression => integer() | nil,
          :output_format => String.t() | nil,
          :user => String.t() | nil,
          :seed => integer() | nil,
          :negative_prompt => String.t() | nil,
          :num_inference_steps => integer() | nil,
          :stream => boolean() | nil,
          :fallbacks => [ExBifrost.Model.Fallback.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:fallbacks, :list, ExBifrost.Model.Fallback)
  end
end
