# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.KeyVertexKeyConfig do
  @moduledoc """
  Vertex-specific key configuration
  """

  @derive JSON.Encoder
  defstruct [
    :project_id,
    :project_number,
    :region,
    :auth_credentials
  ]

  @type t :: %__MODULE__{
          :project_id => ExBifrost.Model.KeyValue.t() | nil,
          :project_number => ExBifrost.Model.KeyValue.t() | nil,
          :region => ExBifrost.Model.KeyValue.t() | nil,
          :auth_credentials => ExBifrost.Model.KeyValue.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:project_id, :struct, ExBifrost.Model.KeyValue)
    |> Deserializer.deserialize(:project_number, :struct, ExBifrost.Model.KeyValue)
    |> Deserializer.deserialize(:region, :struct, ExBifrost.Model.KeyValue)
    |> Deserializer.deserialize(:auth_credentials, :struct, ExBifrost.Model.KeyValue)
  end
end
