# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.KeyBedrockKeyConfigBatchS3Config do
  @moduledoc """
  KeyBedrockKeyConfigBatchS3Config model.
  """

  @derive JSON.Encoder
  defstruct [
    :buckets
  ]

  @type t :: %__MODULE__{
          :buckets => [ExBifrost.Model.KeyBedrockKeyConfigBatchS3ConfigBucketsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:buckets, :list, ExBifrost.Model.KeyBedrockKeyConfigBatchS3ConfigBucketsInner)
  end
end
