# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListPromptSessions200Response do
  @moduledoc """
  ListPromptSessions200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :sessions
  ]

  @type t :: %__MODULE__{
          :sessions => [ExBifrost.Model.ListPrompts200ResponsePromptsInnerSessionsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:sessions, :list, ExBifrost.Model.ListPrompts200ResponsePromptsInnerSessionsInner)
  end
end
