# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListRoutingRulesResponse do
  @moduledoc """
  Response containing list of routing rules
  """

  @derive JSON.Encoder
  defstruct [
    :rules,
    :count
  ]

  @type t :: %__MODULE__{
          :rules => [ExBifrost.Model.RoutingRule.t()] | nil,
          :count => integer() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:rules, :list, ExBifrost.Model.RoutingRule)
  end
end
