# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerMcpToolOverridesInner do
  @moduledoc """
  ListAccessProfiles200ResponseAccessProfilesInnerMcpToolOverridesInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :mcp_client_id,
    :tool_name,
    :action
  ]

  @type t :: %__MODULE__{
          :mcp_client_id => String.t(),
          :tool_name => String.t(),
          :action => String.t()
        }

  def decode(value) do
    value
  end
end
