# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListProvidersResponse do
  @moduledoc """
  List providers response
  """

  @derive JSON.Encoder
  defstruct [
    :providers,
    :total
  ]

  @type t :: %__MODULE__{
          :providers => [ExBifrost.Model.ProviderResponse.t()] | nil,
          :total => integer() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:providers, :list, ExBifrost.Model.ProviderResponse)
  end
end
