# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListCircuitBreakerPolicies200ResponsePoliciesInnerConditionSignalsInner do
  @moduledoc """
  ListCircuitBreakerPolicies200ResponsePoliciesInnerConditionSignalsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :source,
    :header_name,
    :header_value,
    :header_contains
  ]

  @type t :: %__MODULE__{
          :source => String.t(),
          :header_name => String.t(),
          :header_value => String.t() | nil,
          :header_contains => String.t() | nil
        }

  def decode(value) do
    value
  end
end
