# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListFolders200ResponseFoldersInner do
  @moduledoc """
  Prompt folder
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :created_at,
    :updated_at,
    :prompts_count
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil,
          :prompts_count => integer() | nil
        }

  def decode(value) do
    value
  end
end
