# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListVirtualKeysResponse do
  @moduledoc """
  List virtual keys response
  """

  @derive JSON.Encoder
  defstruct [
    :virtual_keys,
    :count,
    :total_count,
    :limit,
    :offset
  ]

  @type t :: %__MODULE__{
          :virtual_keys => [ExBifrost.Model.VirtualKey.t()],
          :count => integer(),
          :total_count => integer(),
          :limit => integer(),
          :offset => integer()
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:virtual_keys, :list, ExBifrost.Model.VirtualKey)
  end
end
