# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListModelsResponse do
  @moduledoc """
  ListModelsResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :extra_fields,
    :next_page_token
  ]

  @type t :: %__MODULE__{
          :data => [ExBifrost.Model.Model.t()] | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil,
          :next_page_token => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:data, :list, ExBifrost.Model.Model)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
