# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListModelConfigsResponse do
  @moduledoc """
  Response containing list of model configs
  """

  @derive JSON.Encoder
  defstruct [
    :model_configs,
    :total_count
  ]

  @type t :: %__MODULE__{
          :model_configs => [ExBifrost.Model.ModelConfig.t()] | nil,
          :total_count => integer() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:model_configs, :list, ExBifrost.Model.ModelConfig)
  end
end
