# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListPrompts200ResponsePromptsInnerLatestVersion do
  @moduledoc """
  Prompt version (immutable snapshot)
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :prompt_id,
    :version_number,
    :commit_message,
    :model_params,
    :provider,
    :model,
    :is_latest,
    :created_at,
    :messages
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :prompt_id => String.t() | nil,
          :version_number => integer() | nil,
          :commit_message => String.t() | nil,
          :model_params => %{optional(String.t()) => any()} | nil,
          :provider => String.t() | nil,
          :model => String.t() | nil,
          :is_latest => boolean() | nil,
          :created_at => DateTime.t() | nil,
          :messages => [ExBifrost.Model.ListPrompts200ResponsePromptsInnerSessionsInnerMessagesInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :messages,
      :list,
      ExBifrost.Model.ListPrompts200ResponsePromptsInnerSessionsInnerMessagesInner
    )
  end
end
