# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListModelDetailsManagement200ResponseModelsInnerArchitecture do
  @moduledoc """
  ListModelDetailsManagement200ResponseModelsInnerArchitecture model.
  """

  @derive JSON.Encoder
  defstruct [
    :modality,
    :tokenizer,
    :instruct_type,
    :input_modalities,
    :output_modalities
  ]

  @type t :: %__MODULE__{
          :modality => String.t() | nil,
          :tokenizer => String.t() | nil,
          :instruct_type => String.t() | nil,
          :input_modalities => [String.t()] | nil,
          :output_modalities => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
