# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListUsers200ResponseUsersInnerRole do
  @moduledoc """
  RBAC role details
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :is_system_role
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :is_system_role => boolean() | nil
        }

  def decode(value) do
    value
  end
end
