# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInner do
  @moduledoc """
  ListAccessProfiles200ResponseAccessProfilesInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :is_active,
    :version,
    :tags,
    :provider_configs,
    :budgets,
    :rate_limit,
    :calendar_aligned,
    :mcp_tool_groups,
    :mcp_servers,
    :mcp_tool_overrides,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :is_active => boolean() | nil,
          :version => integer() | nil,
          :tags => [String.t()] | nil,
          :provider_configs =>
            [ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerProviderConfigsInner.t()] | nil,
          :budgets =>
            [ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerProviderConfigsInnerBudgetsInner.t()] | nil,
          :rate_limit =>
            ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerProviderConfigsInnerRateLimit.t() | nil,
          :calendar_aligned => boolean() | nil,
          :mcp_tool_groups =>
            [ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerMcpToolGroupsInner.t()] | nil,
          :mcp_servers => [ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerMcpServersInner.t()] | nil,
          :mcp_tool_overrides =>
            [ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerMcpToolOverridesInner.t()] | nil,
          :created_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :provider_configs,
      :list,
      ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerProviderConfigsInner
    )
    |> Deserializer.deserialize(
      :budgets,
      :list,
      ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerProviderConfigsInnerBudgetsInner
    )
    |> Deserializer.deserialize(
      :rate_limit,
      :struct,
      ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerProviderConfigsInnerRateLimit
    )
    |> Deserializer.deserialize(
      :mcp_tool_groups,
      :list,
      ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerMcpToolGroupsInner
    )
    |> Deserializer.deserialize(
      :mcp_servers,
      :list,
      ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerMcpServersInner
    )
    |> Deserializer.deserialize(
      :mcp_tool_overrides,
      :list,
      ExBifrost.Model.ListAccessProfiles200ResponseAccessProfilesInnerMcpToolOverridesInner
    )
  end
end
