# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListBusinessUnitTeams200Response do
  @moduledoc """
  Paginated list of teams assigned to a business unit
  """

  @derive JSON.Encoder
  defstruct [
    :teams,
    :total,
    :page,
    :limit
  ]

  @type t :: %__MODULE__{
          :teams => [ExBifrost.Model.CreateTeam200Response.t()],
          :total => integer(),
          :page => integer(),
          :limit => integer()
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:teams, :list, ExBifrost.Model.CreateTeam200Response)
  end
end
