# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListRoles200Response do
  @moduledoc """
  ListRoles200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :roles
  ]

  @type t :: %__MODULE__{
          :roles => [ExBifrost.Model.ListRoles200ResponseRolesInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:roles, :list, ExBifrost.Model.ListRoles200ResponseRolesInner)
  end
end
