# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListAccessProfileVersions200ResponseVersionsInner do
  @moduledoc """
  ListAccessProfileVersions200ResponseVersionsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :access_profile_id,
    :version,
    :name,
    :description,
    :snapshot,
    :changed_by,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :access_profile_id => integer() | nil,
          :version => integer() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :snapshot => String.t() | nil,
          :changed_by => String.t() | nil,
          :created_at => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
