# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListUserAccessProfiles200Response do
  @moduledoc """
  ListUserAccessProfiles200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :access_profiles
  ]

  @type t :: %__MODULE__{
          :access_profiles => [ExBifrost.Model.ListUserAccessProfiles200ResponseAccessProfilesInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :access_profiles,
      :list,
      ExBifrost.Model.ListUserAccessProfiles200ResponseAccessProfilesInner
    )
  end
end
