# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListAccessProfileAuditLogsById200Response do
  @moduledoc """
  ListAccessProfileAuditLogsById200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :audit_logs,
    :total_count
  ]

  @type t :: %__MODULE__{
          :audit_logs => [ExBifrost.Model.ListAccessProfileAuditLogsById200ResponseAuditLogsInner.t()] | nil,
          :total_count => integer() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :audit_logs,
      :list,
      ExBifrost.Model.ListAccessProfileAuditLogsById200ResponseAuditLogsInner
    )
  end
end
