# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListModelsManagement200ResponseModelsInner do
  @moduledoc """
  Model information
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :provider,
    :accessible_by_keys
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :provider => String.t() | nil,
          :accessible_by_keys => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
