# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListContainers200ResponseDataInnerExpiresAfter do
  @moduledoc """
  Expiration configuration for a container
  """

  @derive JSON.Encoder
  defstruct [
    :anchor,
    :minutes
  ]

  @type t :: %__MODULE__{
          :anchor => String.t() | nil,
          :minutes => integer() | nil
        }

  def decode(value) do
    value
  end
end
