# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListPrompts200ResponsePromptsInner do
  @moduledoc """
  Prompt
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :folder_id,
    :folder,
    :created_at,
    :updated_at,
    :versions,
    :sessions,
    :latest_version
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :folder_id => String.t() | nil,
          :folder => ExBifrost.Model.ListFolders200ResponseFoldersInner.t() | nil,
          :created_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil,
          :versions => [ExBifrost.Model.ListPrompts200ResponsePromptsInnerVersionsInner.t()] | nil,
          :sessions => [ExBifrost.Model.ListPrompts200ResponsePromptsInnerSessionsInner.t()] | nil,
          :latest_version => ExBifrost.Model.ListPrompts200ResponsePromptsInnerLatestVersion.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:folder, :struct, ExBifrost.Model.ListFolders200ResponseFoldersInner)
    |> Deserializer.deserialize(:versions, :list, ExBifrost.Model.ListPrompts200ResponsePromptsInnerVersionsInner)
    |> Deserializer.deserialize(:sessions, :list, ExBifrost.Model.ListPrompts200ResponsePromptsInnerSessionsInner)
    |> Deserializer.deserialize(
      :latest_version,
      :struct,
      ExBifrost.Model.ListPrompts200ResponsePromptsInnerLatestVersion
    )
  end
end
