# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ListUsers200Response do
  @moduledoc """
  ListUsers200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :users,
    :total,
    :page,
    :limit,
    :total_pages,
    :has_more
  ]

  @type t :: %__MODULE__{
          :users => [ExBifrost.Model.ListUsers200ResponseUsersInner.t()] | nil,
          :total => integer() | nil,
          :page => integer() | nil,
          :limit => integer() | nil,
          :total_pages => integer() | nil,
          :has_more => boolean() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:users, :list, ExBifrost.Model.ListUsers200ResponseUsersInner)
  end
end
