# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.McpHeadersSubmitRequest do
  @moduledoc """
  Request body for PUT /api/mcp/per-user-headers/flows/{id}. The flow row identifies the (mode, identity, mcp_client) triple, so the caller carries only the values. Extra keys not in the live `per_user_header_keys` schema are dropped server-side. 
  """

  @derive JSON.Encoder
  defstruct [
    :headers
  ]

  @type t :: %__MODULE__{
          :headers => %{optional(String.t()) => String.t()}
        }

  def decode(value) do
    value
  end
end
