# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.McpClient do
  @moduledoc """
  Connected MCP client with its tools
  """

  @derive JSON.Encoder
  defstruct [
    :config,
    :tools,
    :state,
    :vk_configs
  ]

  @type t :: %__MODULE__{
          :config => ExBifrost.Model.McpClientConfig.t() | nil,
          :tools => [ExBifrost.Model.McpClientToolsInner.t()] | nil,
          :state => String.t() | nil,
          :vk_configs => [ExBifrost.Model.McpClientVkConfigsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:config, :struct, ExBifrost.Model.McpClientConfig)
    |> Deserializer.deserialize(:tools, :list, ExBifrost.Model.McpClientToolsInner)
    |> Deserializer.deserialize(:vk_configs, :list, ExBifrost.Model.McpClientVkConfigsInner)
  end
end
