# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.McpClientConfig do
  @moduledoc """
  Full MCP client configuration (used in responses)
  """

  @derive JSON.Encoder
  defstruct [
    :client_id,
    :name,
    :is_code_mode_client,
    :connection_type,
    :connection_string,
    :stdio_config,
    :tls_config,
    :auth_type,
    :oauth_config_id,
    :headers,
    :tools_to_execute,
    :tools_to_auto_execute,
    :tool_pricing,
    :allow_on_all_virtual_keys,
    :per_user_header_keys,
    :disabled
  ]

  @type t :: %__MODULE__{
          :client_id => String.t() | nil,
          :name => String.t() | nil,
          :is_code_mode_client => boolean() | nil,
          :connection_type => String.t() | nil,
          :connection_string => String.t() | nil,
          :stdio_config => ExBifrost.Model.AddMcpClientRequestOneOf2AllOfStdioConfig.t() | nil,
          :tls_config => ExBifrost.Model.AddMcpClientRequestOneOfAllOfTlsConfig.t() | nil,
          :auth_type => String.t() | nil,
          :oauth_config_id => String.t() | nil,
          :headers => %{optional(String.t()) => String.t()} | nil,
          :tools_to_execute => [String.t()] | nil,
          :tools_to_auto_execute => [String.t()] | nil,
          :tool_pricing => %{optional(String.t()) => float()} | nil,
          :allow_on_all_virtual_keys => boolean() | nil,
          :per_user_header_keys => [String.t()] | nil,
          :disabled => boolean() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:stdio_config, :struct, ExBifrost.Model.AddMcpClientRequestOneOf2AllOfStdioConfig)
    |> Deserializer.deserialize(:tls_config, :struct, ExBifrost.Model.AddMcpClientRequestOneOfAllOfTlsConfig)
  end
end
