# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.McpHeadersFlowDetail do
  @moduledoc """
  Response for GET /api/mcp/per-user-headers/flows/{id}. Carries the schema the end-user needs to fill in plus identity binding info for display. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :flow_mode,
    :status,
    :mcp_client,
    :user_id,
    :user,
    :virtual_key,
    :session_id,
    :expires_at,
    :created_at,
    :required_header_keys,
    :admin_header_keys,
    :submitted_keys,
    :has_active_credential
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :flow_mode => String.t(),
          :status => String.t(),
          :mcp_client => ExBifrost.Model.McpClientSummary.t() | nil,
          :user_id => String.t() | nil,
          :user => ExBifrost.Model.McpUserSummary.t() | nil,
          :virtual_key => ExBifrost.Model.McpVirtualKeySummary.t() | nil,
          :session_id => String.t() | nil,
          :expires_at => DateTime.t(),
          :created_at => DateTime.t(),
          :required_header_keys => [String.t()],
          :admin_header_keys => [String.t()] | nil,
          :submitted_keys => [String.t()] | nil,
          :has_active_credential => boolean()
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:mcp_client, :struct, ExBifrost.Model.McpClientSummary)
    |> Deserializer.deserialize(:user, :struct, ExBifrost.Model.McpUserSummary)
    |> Deserializer.deserialize(:virtual_key, :struct, ExBifrost.Model.McpVirtualKeySummary)
  end
end
