# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ModelConfig do
  @moduledoc """
  Model configuration with budget and rate limit settings
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :model_name,
    :provider,
    :scope,
    :scope_id,
    :scope_name,
    :calendar_aligned,
    :budgets,
    :budget,
    :rate_limit,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :model_name => String.t() | nil,
          :provider => String.t() | nil,
          :scope => String.t() | nil,
          :scope_id => String.t() | nil,
          :scope_name => String.t() | nil,
          :calendar_aligned => boolean() | nil,
          :budgets => [ExBifrost.Model.Budget.t()] | nil,
          :budget => ExBifrost.Model.Budget.t() | nil,
          :rate_limit => ExBifrost.Model.RateLimit.t() | nil,
          :created_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:budgets, :list, ExBifrost.Model.Budget)
    |> Deserializer.deserialize(:budget, :struct, ExBifrost.Model.Budget)
    |> Deserializer.deserialize(:rate_limit, :struct, ExBifrost.Model.RateLimit)
  end
end
