# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ModelConfigResponse do
  @moduledoc """
  Response containing a created/updated model config
  """

  @derive JSON.Encoder
  defstruct [
    :message,
    :model_config
  ]

  @type t :: %__MODULE__{
          :message => String.t() | nil,
          :model_config => ExBifrost.Model.ModelConfig.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:model_config, :struct, ExBifrost.Model.ModelConfig)
  end
end
