# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ModelPerRequestLimits do
  @moduledoc """
  ModelPerRequestLimits model.
  """

  @derive JSON.Encoder
  defstruct [
    :prompt_tokens,
    :completion_tokens
  ]

  @type t :: %__MODULE__{
          :prompt_tokens => integer() | nil,
          :completion_tokens => integer() | nil
        }

  def decode(value) do
    value
  end
end
