# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ModelTopProvider do
  @moduledoc """
  ModelTopProvider model.
  """

  @derive JSON.Encoder
  defstruct [
    :is_moderated,
    :context_length,
    :max_completion_tokens
  ]

  @type t :: %__MODULE__{
          :is_moderated => boolean() | nil,
          :context_length => integer() | nil,
          :max_completion_tokens => integer() | nil
        }

  def decode(value) do
    value
  end
end
