# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OAuthConfigStatus do
  @moduledoc """
  Status of an OAuth configuration
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :status,
    :created_at,
    :expires_at,
    :token_id,
    :token_expires_at,
    :token_scopes
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :status => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :expires_at => DateTime.t() | nil,
          :token_id => String.t() | nil,
          :token_expires_at => DateTime.t() | nil,
          :token_scopes => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
