# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OAuthToken do
  @moduledoc """
  OAuth access and refresh tokens
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :access_token,
    :refresh_token,
    :token_type,
    :expires_at,
    :scopes,
    :last_refreshed_at
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :access_token => String.t() | nil,
          :refresh_token => String.t() | nil,
          :token_type => String.t() | nil,
          :expires_at => DateTime.t() | nil,
          :scopes => [String.t()] | nil,
          :last_refreshed_at => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
