# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OcrDocument do
  @moduledoc """
  OcrDocument model.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :document_url,
    :image_url
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :document_url => String.t() | nil,
          :image_url => String.t() | nil
        }

  def decode(value) do
    value
  end
end
