# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OcrRequestBboxAnnotationFormat do
  @moduledoc """
  Format for bounding box annotations. Supports text, json_object, and json_schema modes.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :json_schema
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :json_schema => ExBifrost.Model.OcrRequestBboxAnnotationFormatJsonSchema.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:json_schema, :struct, ExBifrost.Model.OcrRequestBboxAnnotationFormatJsonSchema)
  end
end
