# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OcrRequestBboxAnnotationFormatJsonSchema do
  @moduledoc """
  JSON schema definition (required when type is json_schema)
  """

  @derive JSON.Encoder
  defstruct [
    :schema,
    :name,
    :strict
  ]

  @type t :: %__MODULE__{
          :schema => map() | nil,
          :name => String.t() | nil,
          :strict => boolean() | nil
        }

  def decode(value) do
    value
  end
end
