# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OcrUsageInfo do
  @moduledoc """
  OcrUsageInfo model.
  """

  @derive JSON.Encoder
  defstruct [
    :pages_processed,
    :doc_size_bytes
  ]

  @type t :: %__MODULE__{
          :pages_processed => integer(),
          :doc_size_bytes => integer()
        }

  def decode(value) do
    value
  end
end
