# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OcrPageConfidenceScores do
  @moduledoc """
  Confidence scores for this page (present when confidence_scores_granularity is set)
  """

  @derive JSON.Encoder
  defstruct [
    :average_page_confidence_score,
    :minimum_page_confidence_score,
    :word_confidence_scores
  ]

  @type t :: %__MODULE__{
          :average_page_confidence_score => number() | nil,
          :minimum_page_confidence_score => number() | nil,
          :word_confidence_scores => [number()] | nil
        }

  def decode(value) do
    value
  end
end
