# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OpenaiUploadFileRequestStorageConfig do
  @moduledoc """
  Storage configuration for cloud storage backends
  """

  @derive JSON.Encoder
  defstruct [
    :s3,
    :gcs
  ]

  @type t :: %__MODULE__{
          :s3 => ExBifrost.Model.OpenaiUploadFileRequestStorageConfigS3.t() | nil,
          :gcs => ExBifrost.Model.OpenaiUploadFileRequestStorageConfigGcs.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:s3, :struct, ExBifrost.Model.OpenaiUploadFileRequestStorageConfigS3)
    |> Deserializer.deserialize(:gcs, :struct, ExBifrost.Model.OpenaiUploadFileRequestStorageConfigGcs)
  end
end
