# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OpenAiResponsesRequestReasoning do
  @moduledoc """
  OpenAiResponsesRequestReasoning model.
  """

  @derive JSON.Encoder
  defstruct [
    :effort,
    :generate_summary,
    :summary,
    :max_tokens
  ]

  @type t :: %__MODULE__{
          :effort => String.t() | nil,
          :generate_summary => String.t() | nil,
          :summary => String.t() | nil,
          :max_tokens => integer() | nil
        }

  def decode(value) do
    value
  end
end
