# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OpenAiEmbeddingRequest do
  @moduledoc """
  OpenAiEmbeddingRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :input,
    :encoding_format,
    :dimensions,
    :user,
    :fallbacks
  ]

  @type t :: %__MODULE__{
          :model => String.t(),
          :input => ExBifrost.Model.ChatCompletionRequestStop.t(),
          :encoding_format => String.t() | nil,
          :dimensions => integer() | nil,
          :user => String.t() | nil,
          :fallbacks => [String.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:input, :struct, ExBifrost.Model.ChatCompletionRequestStop)
  end
end
