# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.OpenAiResponsesRequest do
  @moduledoc """
  OpenAiResponsesRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :input,
    :stream,
    :instructions,
    :max_output_tokens,
    :metadata,
    :parallel_tool_calls,
    :previous_response_id,
    :reasoning,
    :store,
    :temperature,
    :text,
    :tool_choice,
    :tools,
    :top_p,
    :truncation,
    :user,
    :fallbacks
  ]

  @type t :: %__MODULE__{
          :model => String.t(),
          :input => ExBifrost.Model.CreateCompactionRequestInput.t(),
          :stream => boolean() | nil,
          :instructions => String.t() | nil,
          :max_output_tokens => integer() | nil,
          :metadata => %{optional(String.t()) => any()} | nil,
          :parallel_tool_calls => boolean() | nil,
          :previous_response_id => String.t() | nil,
          :reasoning => ExBifrost.Model.OpenAiResponsesRequestReasoning.t() | nil,
          :store => boolean() | nil,
          :temperature => number() | nil,
          :text => ExBifrost.Model.OpenAiResponsesRequestText.t() | nil,
          :tool_choice => ExBifrost.Model.ResponsesRequestToolChoice.t() | nil,
          :tools => [ExBifrost.Model.ResponsesRequestToolsInner.t()] | nil,
          :top_p => number() | nil,
          :truncation => String.t() | nil,
          :user => String.t() | nil,
          :fallbacks => [String.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:input, :struct, ExBifrost.Model.CreateCompactionRequestInput)
    |> Deserializer.deserialize(:reasoning, :struct, ExBifrost.Model.OpenAiResponsesRequestReasoning)
    |> Deserializer.deserialize(:text, :struct, ExBifrost.Model.OpenAiResponsesRequestText)
    |> Deserializer.deserialize(:tool_choice, :struct, ExBifrost.Model.ResponsesRequestToolChoice)
    |> Deserializer.deserialize(:tools, :list, ExBifrost.Model.ResponsesRequestToolsInner)
  end
end
