# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.PricingOverrideResponse do
  @moduledoc """
  PricingOverrideResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :message,
    :pricing_override
  ]

  @type t :: %__MODULE__{
          :message => String.t() | nil,
          :pricing_override => ExBifrost.Model.PricingOverride.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:pricing_override, :struct, ExBifrost.Model.PricingOverride)
  end
end
