# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ProviderResponseCustomProviderConfigAllowedRequests do
  @moduledoc """
  Allowed request types for custom providers
  """

  @derive JSON.Encoder
  defstruct [
    :list_models,
    :text_completion,
    :text_completion_stream,
    :chat_completion,
    :chat_completion_stream,
    :responses,
    :responses_stream,
    :count_tokens,
    :embedding,
    :speech,
    :speech_stream,
    :transcription,
    :transcription_stream,
    :image_generation,
    :image_generation_stream,
    :batch_create,
    :batch_list,
    :batch_retrieve,
    :batch_cancel,
    :batch_results,
    :file_upload,
    :file_list,
    :file_retrieve,
    :file_delete,
    :file_content
  ]

  @type t :: %__MODULE__{
          :list_models => boolean() | nil,
          :text_completion => boolean() | nil,
          :text_completion_stream => boolean() | nil,
          :chat_completion => boolean() | nil,
          :chat_completion_stream => boolean() | nil,
          :responses => boolean() | nil,
          :responses_stream => boolean() | nil,
          :count_tokens => boolean() | nil,
          :embedding => boolean() | nil,
          :speech => boolean() | nil,
          :speech_stream => boolean() | nil,
          :transcription => boolean() | nil,
          :transcription_stream => boolean() | nil,
          :image_generation => boolean() | nil,
          :image_generation_stream => boolean() | nil,
          :batch_create => boolean() | nil,
          :batch_list => boolean() | nil,
          :batch_retrieve => boolean() | nil,
          :batch_cancel => boolean() | nil,
          :batch_results => boolean() | nil,
          :file_upload => boolean() | nil,
          :file_list => boolean() | nil,
          :file_retrieve => boolean() | nil,
          :file_delete => boolean() | nil,
          :file_content => boolean() | nil
        }

  def decode(value) do
    value
  end
end
