# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ProviderResponseProxyConfig do
  @moduledoc """
  Proxy configuration
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :url,
    :username,
    :password,
    :ca_cert_pem
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :url => String.t() | nil,
          :username => String.t() | nil,
          :password => String.t() | nil,
          :ca_cert_pem => String.t() | nil
        }

  def decode(value) do
    value
  end
end
