# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ProviderResponseCustomProviderConfig do
  @moduledoc """
  Custom provider configuration
  """

  @derive JSON.Encoder
  defstruct [
    :is_key_less,
    :base_provider_type,
    :allowed_requests,
    :request_path_overrides
  ]

  @type t :: %__MODULE__{
          :is_key_less => boolean() | nil,
          :base_provider_type => ExBifrost.Model.ModelProvider.t() | nil,
          :allowed_requests => ExBifrost.Model.ProviderResponseCustomProviderConfigAllowedRequests.t() | nil,
          :request_path_overrides => %{optional(String.t()) => String.t()} | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:base_provider_type, :struct, ExBifrost.Model.ModelProvider)
    |> Deserializer.deserialize(
      :allowed_requests,
      :struct,
      ExBifrost.Model.ProviderResponseCustomProviderConfigAllowedRequests
    )
  end
end
