# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.RateLimit do
  @moduledoc """
  Rate limit configuration
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :token_max_limit,
    :token_reset_duration,
    :token_current_usage,
    :token_last_reset,
    :request_max_limit,
    :request_reset_duration,
    :request_current_usage,
    :request_last_reset,
    :config_hash,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :token_max_limit => integer() | nil,
          :token_reset_duration => String.t() | nil,
          :token_current_usage => integer(),
          :token_last_reset => DateTime.t(),
          :request_max_limit => integer() | nil,
          :request_reset_duration => String.t() | nil,
          :request_current_usage => integer(),
          :request_last_reset => DateTime.t(),
          :config_hash => String.t() | nil,
          :created_at => DateTime.t(),
          :updated_at => DateTime.t()
        }

  def decode(value) do
    value
  end
end
