# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.RecalculateCostRequest do
  @moduledoc """
  Recalculate cost request
  """

  @derive JSON.Encoder
  defstruct [
    :filters,
    :limit
  ]

  @type t :: %__MODULE__{
          :filters => ExBifrost.Model.RecalculateCostRequestFilters.t() | nil,
          :limit => integer() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:filters, :struct, ExBifrost.Model.RecalculateCostRequestFilters)
  end
end
