# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ResponsesRequestToolChoiceOneOf do
  @moduledoc """
  ResponsesRequestToolChoiceOneOf model.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :mode,
    :name,
    :server_label,
    :tools
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :mode => String.t() | nil,
          :name => String.t() | nil,
          :server_label => String.t() | nil,
          :tools => [ExBifrost.Model.ResponsesRequestToolChoiceOneOfToolsInner.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:tools, :list, ExBifrost.Model.ResponsesRequestToolChoiceOneOfToolsInner)
  end
end
