# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.Responses1 do
  @moduledoc """
  Responses format - uses ResponsesToolMessage schema
  """

  @derive JSON.Encoder
  defstruct [
    :call_id,
    :name,
    :arguments,
    :output,
    :action,
    :error
  ]

  @type t :: %__MODULE__{
          :call_id => String.t() | nil,
          :name => String.t(),
          :arguments => String.t() | nil,
          :output => %{optional(String.t()) => any()} | nil,
          :action => %{optional(String.t()) => any()} | nil,
          :error => String.t() | nil
        }

  def decode(value) do
    value
  end
end
