# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ResponsesRequest do
  @moduledoc """
  ResponsesRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :input,
    :fallbacks,
    :stream,
    :background,
    :conversation,
    :include,
    :instructions,
    :max_output_tokens,
    :max_tool_calls,
    :metadata,
    :parallel_tool_calls,
    :previous_response_id,
    :prompt_cache_key,
    :reasoning,
    :safety_identifier,
    :service_tier,
    :stream_options,
    :store,
    :temperature,
    :text,
    :top_logprobs,
    :top_p,
    :tool_choice,
    :tools,
    :truncation
  ]

  @type t :: %__MODULE__{
          :model => String.t(),
          :input => ExBifrost.Model.CreateCompactionRequestInput.t(),
          :fallbacks => [String.t()] | nil,
          :stream => boolean() | nil,
          :background => boolean() | nil,
          :conversation => String.t() | nil,
          :include => [String.t()] | nil,
          :instructions => String.t() | nil,
          :max_output_tokens => integer() | nil,
          :max_tool_calls => integer() | nil,
          :metadata => %{optional(String.t()) => any()} | nil,
          :parallel_tool_calls => boolean() | nil,
          :previous_response_id => String.t() | nil,
          :prompt_cache_key => String.t() | nil,
          :reasoning => ExBifrost.Model.ResponsesRequestReasoning.t() | nil,
          :safety_identifier => String.t() | nil,
          :service_tier => String.t() | nil,
          :stream_options => ExBifrost.Model.ResponsesRequestStreamOptions.t() | nil,
          :store => boolean() | nil,
          :temperature => number() | nil,
          :text => ExBifrost.Model.ResponsesRequestText.t() | nil,
          :top_logprobs => integer() | nil,
          :top_p => number() | nil,
          :tool_choice => ExBifrost.Model.ResponsesRequestToolChoice.t() | nil,
          :tools => [ExBifrost.Model.ResponsesRequestToolsInner.t()] | nil,
          :truncation => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:input, :struct, ExBifrost.Model.CreateCompactionRequestInput)
    |> Deserializer.deserialize(:reasoning, :struct, ExBifrost.Model.ResponsesRequestReasoning)
    |> Deserializer.deserialize(:stream_options, :struct, ExBifrost.Model.ResponsesRequestStreamOptions)
    |> Deserializer.deserialize(:text, :struct, ExBifrost.Model.ResponsesRequestText)
    |> Deserializer.deserialize(:tool_choice, :struct, ExBifrost.Model.ResponsesRequestToolChoice)
    |> Deserializer.deserialize(:tools, :list, ExBifrost.Model.ResponsesRequestToolsInner)
  end
end
