# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.ResponsesResponse do
  @moduledoc """
  ResponsesResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :background,
    :conversation,
    :created_at,
    :error,
    :include,
    :incomplete_details,
    :instructions,
    :max_output_tokens,
    :max_tool_calls,
    :metadata,
    :model,
    :output,
    :parallel_tool_calls,
    :previous_response_id,
    :prompt,
    :prompt_cache_key,
    :reasoning,
    :safety_identifier,
    :service_tier,
    :status,
    :stop_reason,
    :store,
    :temperature,
    :text,
    :top_logprobs,
    :top_p,
    :tool_choice,
    :tools,
    :truncation,
    :usage,
    :extra_fields,
    :search_results,
    :videos,
    :citations
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :background => boolean() | nil,
          :conversation => map() | nil,
          :created_at => integer() | nil,
          :error => ExBifrost.Model.ResponsesResponseError.t() | nil,
          :include => [String.t()] | nil,
          :incomplete_details => ExBifrost.Model.ResponsesResponseIncompleteDetails.t() | nil,
          :instructions => map() | nil,
          :max_output_tokens => integer() | nil,
          :max_tool_calls => integer() | nil,
          :metadata => map() | nil,
          :model => String.t() | nil,
          :output => [ExBifrost.Model.CreateResponse200ResponseItem.t()] | nil,
          :parallel_tool_calls => boolean() | nil,
          :previous_response_id => String.t() | nil,
          :prompt => map() | nil,
          :prompt_cache_key => String.t() | nil,
          :reasoning => ExBifrost.Model.ResponsesRequestReasoning.t() | nil,
          :safety_identifier => String.t() | nil,
          :service_tier => String.t() | nil,
          :status => String.t() | nil,
          :stop_reason => String.t() | nil,
          :store => boolean() | nil,
          :temperature => number() | nil,
          :text => ExBifrost.Model.ResponsesRequestText.t() | nil,
          :top_logprobs => integer() | nil,
          :top_p => number() | nil,
          :tool_choice => ExBifrost.Model.ResponsesRequestToolChoice.t() | nil,
          :tools => [ExBifrost.Model.ResponsesRequestToolsInner.t()] | nil,
          :truncation => String.t() | nil,
          :usage => ExBifrost.Model.CreateCompaction200ResponseUsage.t() | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil,
          :search_results => [ExBifrost.Model.PerplexitySearchResult.t()] | nil,
          :videos => [ExBifrost.Model.PerplexityVideoResult.t()] | nil,
          :citations => [String.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:error, :struct, ExBifrost.Model.ResponsesResponseError)
    |> Deserializer.deserialize(:incomplete_details, :struct, ExBifrost.Model.ResponsesResponseIncompleteDetails)
    |> Deserializer.deserialize(:output, :list, ExBifrost.Model.CreateResponse200ResponseItem)
    |> Deserializer.deserialize(:reasoning, :struct, ExBifrost.Model.ResponsesRequestReasoning)
    |> Deserializer.deserialize(:text, :struct, ExBifrost.Model.ResponsesRequestText)
    |> Deserializer.deserialize(:tool_choice, :struct, ExBifrost.Model.ResponsesRequestToolChoice)
    |> Deserializer.deserialize(:tools, :list, ExBifrost.Model.ResponsesRequestToolsInner)
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.CreateCompaction200ResponseUsage)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
    |> Deserializer.deserialize(:search_results, :list, ExBifrost.Model.PerplexitySearchResult)
    |> Deserializer.deserialize(:videos, :list, ExBifrost.Model.PerplexityVideoResult)
  end
end
