# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.RoutingRuleOneOf1 do
  @moduledoc """
  Scoped routing rule (requires scope_id)
  """

  @derive JSON.Encoder
  defstruct [
    :scope,
    :scope_id
  ]

  @type t :: %__MODULE__{
          :scope => String.t(),
          :scope_id => String.t()
        }

  def decode(value) do
    value
  end
end
