# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.Skill do
  @moduledoc """
  Skill repository entry and currently served version metadata.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :license,
    :compatibility,
    :metadata,
    :extra_frontmatter,
    :allowed_tools,
    :skill_md_body,
    :latest_version,
    :created_by,
    :created_at,
    :updated_at,
    :files,
    :file_count,
    :highest_version
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :license => String.t() | nil,
          :compatibility => String.t() | nil,
          :metadata => %{optional(String.t()) => String.t()} | nil,
          :extra_frontmatter => %{optional(String.t()) => any()} | nil,
          :allowed_tools => String.t() | nil,
          :skill_md_body => String.t() | nil,
          :latest_version => String.t() | nil,
          :created_by => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil,
          :files => [ExBifrost.Model.SkillFile.t()] | nil,
          :file_count => integer() | nil,
          :highest_version => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:files, :list, ExBifrost.Model.SkillFile)
  end
end
