# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.SkillVersion do
  @moduledoc """
  Immutable skill version snapshot.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :skill_id,
    :version,
    :skill_md_body,
    :frontmatter_snapshot,
    :created_by,
    :created_at,
    :files
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :skill_id => String.t() | nil,
          :version => String.t() | nil,
          :skill_md_body => String.t() | nil,
          :frontmatter_snapshot => %{optional(String.t()) => any()} | nil,
          :created_by => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :files => [ExBifrost.Model.SkillFile.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:files, :list, ExBifrost.Model.SkillFile)
  end
end
