# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.SpeechResponse do
  @moduledoc """
  SpeechResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :audio,
    :usage,
    :alignment,
    :normalized_alignment,
    :audio_base64,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :audio => binary() | nil,
          :usage => ExBifrost.Model.CreateSpeech200ResponseUsage.t() | nil,
          :alignment => ExBifrost.Model.SpeechResponseAlignment.t() | nil,
          :normalized_alignment => ExBifrost.Model.SpeechResponseAlignment.t() | nil,
          :audio_base64 => String.t() | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.CreateSpeech200ResponseUsage)
    |> Deserializer.deserialize(:alignment, :struct, ExBifrost.Model.SpeechResponseAlignment)
    |> Deserializer.deserialize(:normalized_alignment, :struct, ExBifrost.Model.SpeechResponseAlignment)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
