# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.SuccessResponse do
  @moduledoc """
  Generic success response
  """

  @derive JSON.Encoder
  defstruct [
    :status,
    :message
  ]

  @type t :: %__MODULE__{
          :status => String.t() | nil,
          :message => String.t() | nil
        }

  def decode(value) do
    value
  end
end
