# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.TeamResponse do
  @moduledoc """
  Team operation response
  """

  @derive JSON.Encoder
  defstruct [
    :message,
    :team
  ]

  @type t :: %__MODULE__{
          :message => String.t() | nil,
          :team => ExBifrost.Model.Team.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:team, :struct, ExBifrost.Model.Team)
  end
end
