# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.TestWebhookResponse do
  @moduledoc """
  TestWebhookResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :delivered,
    :receiver_status_code,
    :error
  ]

  @type t :: %__MODULE__{
          :delivered => boolean() | nil,
          :receiver_status_code => integer() | nil,
          :error => String.t() | nil
        }

  def decode(value) do
    value
  end
end
