# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.TranscriptionResponse do
  @moduledoc """
  TranscriptionResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :duration,
    :language,
    :logprobs,
    :segments,
    :task,
    :text,
    :usage,
    :words,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :duration => number() | nil,
          :language => String.t() | nil,
          :logprobs =>
            [ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerLogProbsContentInnerTopLogprobsInner.t()] | nil,
          :segments => [ExBifrost.Model.TranscriptionResponseSegmentsInner.t()] | nil,
          :task => String.t() | nil,
          :text => String.t() | nil,
          :usage => ExBifrost.Model.CreateTranscription200ResponseUsage.t() | nil,
          :words => [ExBifrost.Model.TranscriptionResponseWordsInner.t()] | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :logprobs,
      :list,
      ExBifrost.Model.CreateChatCompletion200ResponseChoicesInnerLogProbsContentInnerTopLogprobsInner
    )
    |> Deserializer.deserialize(:segments, :list, ExBifrost.Model.TranscriptionResponseSegmentsInner)
    |> Deserializer.deserialize(:usage, :struct, ExBifrost.Model.CreateTranscription200ResponseUsage)
    |> Deserializer.deserialize(:words, :list, ExBifrost.Model.TranscriptionResponseWordsInner)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
