# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.UpdateMcpToolGroupRequest do
  @moduledoc """
  Partial update. - Scalar fields (`name`, `description`, `enabled`) preserve the current value when omitted. - Array fields are replace-on-send: whatever you provide becomes the new full value. To clear an attachment dimension, send an empty array. 
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description,
    :enabled,
    :tools,
    :virtual_key_ids,
    :team_ids,
    :customer_ids,
    :user_ids,
    :provider_names,
    :api_key_ids
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :description => String.t() | nil,
          :enabled => boolean() | nil,
          :tools => [ExBifrost.Model.ListMcpToolGroups200ResponseMcpToolGroupsInnerToolsInner.t()] | nil,
          :virtual_key_ids => [String.t()] | nil,
          :team_ids => [String.t()] | nil,
          :customer_ids => [String.t()] | nil,
          :user_ids => [String.t()] | nil,
          :provider_names => [String.t()] | nil,
          :api_key_ids => [integer()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:tools, :list, ExBifrost.Model.ListMcpToolGroups200ResponseMcpToolGroupsInnerToolsInner)
  end
end
