# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.UpdateVirtualKeyRequestProviderConfigsInner do
  @moduledoc """
  UpdateVirtualKeyRequestProviderConfigsInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :provider,
    :weight,
    :allowed_models,
    :blacklisted_models,
    :budgets,
    :rate_limit,
    :key_ids
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :provider => String.t() | nil,
          :weight => number() | nil,
          :allowed_models => [String.t()] | nil,
          :blacklisted_models => [String.t()] | nil,
          :budgets => [ExBifrost.Model.CreateBudgetRequest.t()] | nil,
          :rate_limit => ExBifrost.Model.UpdateRateLimitRequest.t() | nil,
          :key_ids => [String.t()] | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:budgets, :list, ExBifrost.Model.CreateBudgetRequest)
    |> Deserializer.deserialize(:rate_limit, :struct, ExBifrost.Model.UpdateRateLimitRequest)
  end
end
