# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.UpdateRolePermissionsRequest do
  @moduledoc """
  UpdateRolePermissionsRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :permission_ids
  ]

  @type t :: %__MODULE__{
          :permission_ids => [integer()]
        }

  def decode(value) do
    value
  end
end
