# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.UpdateFolderRequest do
  @moduledoc """
  UpdateFolderRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :description => String.t() | nil
        }

  def decode(value) do
    value
  end
end
