# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.UpdateVirtualKeyRequest do
  @moduledoc """
  Update virtual key request
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description,
    :provider_configs,
    :mcp_configs,
    :team_id,
    :customer_id,
    :budgets,
    :rate_limit,
    :is_active,
    :calendar_aligned,
    :reset_budget_usage,
    :expires_at
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :description => String.t() | nil,
          :provider_configs => [ExBifrost.Model.UpdateVirtualKeyRequestProviderConfigsInner.t()] | nil,
          :mcp_configs => [ExBifrost.Model.UpdateVirtualKeyRequestMcpConfigsInner.t()] | nil,
          :team_id => String.t() | nil,
          :customer_id => String.t() | nil,
          :budgets => [ExBifrost.Model.CreateBudgetRequest.t()] | nil,
          :rate_limit => ExBifrost.Model.UpdateRateLimitRequest.t() | nil,
          :is_active => boolean() | nil,
          :calendar_aligned => boolean() | nil,
          :reset_budget_usage => boolean() | nil,
          :expires_at => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:provider_configs, :list, ExBifrost.Model.UpdateVirtualKeyRequestProviderConfigsInner)
    |> Deserializer.deserialize(:mcp_configs, :list, ExBifrost.Model.UpdateVirtualKeyRequestMcpConfigsInner)
    |> Deserializer.deserialize(:budgets, :list, ExBifrost.Model.CreateBudgetRequest)
    |> Deserializer.deserialize(:rate_limit, :struct, ExBifrost.Model.UpdateRateLimitRequest)
  end
end
