# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.UpdatePricingOverrideRequest do
  @moduledoc """
  Request body for updating a pricing override. All fields are optional - omitted fields are merged from the existing record. The `patch` field is always replaced in full when provided. 
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :scope_kind,
    :virtual_key_id,
    :provider_id,
    :provider_key_id,
    :match_type,
    :pattern,
    :request_types,
    :patch
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :scope_kind => String.t() | nil,
          :virtual_key_id => String.t() | nil,
          :provider_id => String.t() | nil,
          :provider_key_id => String.t() | nil,
          :match_type => String.t() | nil,
          :pattern => String.t() | nil,
          :request_types => [ExBifrost.Model.PricingOverrideRequestType.t()] | nil,
          :patch => ExBifrost.Model.PricingPatch.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:request_types, :list, ExBifrost.Model.PricingOverrideRequestType)
    |> Deserializer.deserialize(:patch, :struct, ExBifrost.Model.PricingPatch)
  end
end
