# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.UpdateConfigRequest do
  @moduledoc """
  Update configuration request
  """

  @derive JSON.Encoder
  defstruct [
    :client_config,
    :framework_config,
    :auth_config
  ]

  @type t :: %__MODULE__{
          :client_config => ExBifrost.Model.GetConfigResponseClientConfig.t() | nil,
          :framework_config => ExBifrost.Model.GetConfigResponseFrameworkConfig.t() | nil,
          :auth_config => ExBifrost.Model.GetConfigResponseAuthConfig.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:client_config, :struct, ExBifrost.Model.GetConfigResponseClientConfig)
    |> Deserializer.deserialize(:framework_config, :struct, ExBifrost.Model.GetConfigResponseFrameworkConfig)
    |> Deserializer.deserialize(:auth_config, :struct, ExBifrost.Model.GetConfigResponseAuthConfig)
  end
end
