# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.UpdateProviderRequest do
  @moduledoc """
  Update provider request. Keys are managed separately via /api/providers/{provider}/keys.
  """

  @derive JSON.Encoder
  defstruct [
    :network_config,
    :concurrency_and_buffer_size,
    :proxy_config,
    :send_back_raw_request,
    :send_back_raw_response,
    :store_raw_request_response,
    :custom_provider_config
  ]

  @type t :: %__MODULE__{
          :network_config => ExBifrost.Model.NetworkConfig.t() | nil,
          :concurrency_and_buffer_size => ExBifrost.Model.ConcurrencyAndBufferSize.t() | nil,
          :proxy_config => ExBifrost.Model.ProviderResponseProxyConfig.t() | nil,
          :send_back_raw_request => boolean() | nil,
          :send_back_raw_response => boolean() | nil,
          :store_raw_request_response => boolean() | nil,
          :custom_provider_config => ExBifrost.Model.ProviderResponseCustomProviderConfig.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:network_config, :struct, ExBifrost.Model.NetworkConfig)
    |> Deserializer.deserialize(:concurrency_and_buffer_size, :struct, ExBifrost.Model.ConcurrencyAndBufferSize)
    |> Deserializer.deserialize(:proxy_config, :struct, ExBifrost.Model.ProviderResponseProxyConfig)
    |> Deserializer.deserialize(:custom_provider_config, :struct, ExBifrost.Model.ProviderResponseCustomProviderConfig)
  end
end
