# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.VertexRankRequest do
  @moduledoc """
  VertexRankRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :model,
    :query,
    :records,
    :topN,
    :ignoreRecordDetailsInResponse
  ]

  @type t :: %__MODULE__{
          :model => String.t() | nil,
          :query => String.t() | nil,
          :records => [ExBifrost.Model.VertexRankRequestRecordsInner.t()] | nil,
          :topN => integer() | nil,
          :ignoreRecordDetailsInResponse => boolean() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:records, :list, ExBifrost.Model.VertexRankRequestRecordsInner)
  end
end
