# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.VideoList200Response do
  @moduledoc """
  VideoList200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :object,
    :data,
    :first_id,
    :last_id,
    :has_more,
    :extra_fields
  ]

  @type t :: %__MODULE__{
          :object => String.t() | nil,
          :data => [ExBifrost.Model.VideoList200ResponseDataInner.t()] | nil,
          :first_id => String.t() | nil,
          :last_id => String.t() | nil,
          :has_more => boolean() | nil,
          :extra_fields => ExBifrost.Model.BifrostResponseExtraFields.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:data, :list, ExBifrost.Model.VideoList200ResponseDataInner)
    |> Deserializer.deserialize(:extra_fields, :struct, ExBifrost.Model.BifrostResponseExtraFields)
  end
end
