# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.VideoList200ResponseDataInner do
  @moduledoc """
  VideoList200ResponseDataInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :object,
    :model,
    :status,
    :progress,
    :prompt,
    :remixed_from_video_id,
    :seconds,
    :size,
    :created_at,
    :completed_at,
    :expires_at,
    :error
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :object => String.t() | nil,
          :model => String.t() | nil,
          :status => String.t() | nil,
          :progress => float() | nil,
          :prompt => String.t() | nil,
          :remixed_from_video_id => String.t() | nil,
          :seconds => String.t() | nil,
          :size => String.t() | nil,
          :created_at => integer() | nil,
          :completed_at => integer() | nil,
          :expires_at => integer() | nil,
          :error => ExBifrost.Model.VideoList200ResponseDataInnerError.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:error, :struct, ExBifrost.Model.VideoList200ResponseDataInnerError)
  end
end
