# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.VirtualKeyQuotaResponse do
  @moduledoc """
  Virtual key quota response (self-service, no admin auth required)
  """

  @derive JSON.Encoder
  defstruct [
    :virtual_key_name,
    :is_active,
    :budgets,
    :rate_limit,
    :provider_configs,
    :model_configs
  ]

  @type t :: %__MODULE__{
          :virtual_key_name => String.t(),
          :is_active => boolean(),
          :budgets => [ExBifrost.Model.VirtualKeyQuotaResponseBudgetsInner.t()] | nil,
          :rate_limit => ExBifrost.Model.RateLimit.t() | nil,
          :provider_configs => [ExBifrost.Model.VirtualKeyProviderConfig.t()] | nil,
          :model_configs => [ExBifrost.Model.VirtualKeyQuotaResponseModelConfigsInner.t()]
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:budgets, :list, ExBifrost.Model.VirtualKeyQuotaResponseBudgetsInner)
    |> Deserializer.deserialize(:rate_limit, :struct, ExBifrost.Model.RateLimit)
    |> Deserializer.deserialize(:provider_configs, :list, ExBifrost.Model.VirtualKeyProviderConfig)
    |> Deserializer.deserialize(:model_configs, :list, ExBifrost.Model.VirtualKeyQuotaResponseModelConfigsInner)
  end
end
