# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.VirtualKeyQuotaResponseModelConfigsInner do
  @moduledoc """
  Per-model budgets and rate limit (with current usage) for a model governed under a virtual key
  """

  @derive JSON.Encoder
  defstruct [
    :model_name,
    :provider,
    :budgets,
    :rate_limit
  ]

  @type t :: %__MODULE__{
          :model_name => String.t(),
          :provider => String.t() | nil,
          :budgets => [ExBifrost.Model.Budget.t()] | nil,
          :rate_limit => ExBifrost.Model.RateLimit.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:budgets, :list, ExBifrost.Model.Budget)
    |> Deserializer.deserialize(:rate_limit, :struct, ExBifrost.Model.RateLimit)
  end
end
