# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.WebhookDeliveryOutcome do
  @moduledoc """
  Outcome of a single delivery attempt: - delivered: the receiver returned 2xx - retryable_failure: failed but will be retried - permanent_failure: failed in a way that is not retried - exhausted: retries were used up without success 
  """

  @derive JSON.Encoder
  defstruct []

  @type t :: %__MODULE__{}

  def decode(value) do
    value
  end
end
