# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.WebhookDelivery do
  @moduledoc """
  One delivery attempt in an endpoint's history.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :webhook_id,
    :endpoint_id,
    :async_job_id,
    :request_id,
    :event,
    :attempt_no,
    :outcome,
    :status_code,
    :error,
    :created_at,
    :expires_at
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :webhook_id => String.t() | nil,
          :endpoint_id => String.t() | nil,
          :async_job_id => String.t() | nil,
          :request_id => String.t() | nil,
          :event => ExBifrost.Model.WebhookEvent.t() | nil,
          :attempt_no => integer() | nil,
          :outcome => ExBifrost.Model.WebhookDeliveryOutcome.t() | nil,
          :status_code => integer() | nil,
          :error => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :expires_at => DateTime.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:event, :struct, ExBifrost.Model.WebhookEvent)
    |> Deserializer.deserialize(:outcome, :struct, ExBifrost.Model.WebhookDeliveryOutcome)
  end
end
