# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.WebhookEndpoint do
  @moduledoc """
  A registered webhook endpoint. The signing secret is never included in this representation; custom header values are redacted. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :url,
    :events,
    :headers,
    :include_response,
    :allow_private_network,
    :disabled,
    :max_retries,
    :retry_backoff_initial_seconds,
    :retry_backoff_max_seconds,
    :attempt_timeout_seconds,
    :max_response_payload_kbs,
    :max_concurrent_deliveries,
    :consecutive_failures,
    :last_success_at,
    :last_failure_at,
    :config_hash,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :url => String.t() | nil,
          :events => [ExBifrost.Model.WebhookEvent.t()] | nil,
          :headers => %{optional(String.t()) => ExBifrost.Model.WebhookEndpointHeadersValue.t()} | nil,
          :include_response => boolean() | nil,
          :allow_private_network => boolean() | nil,
          :disabled => boolean() | nil,
          :max_retries => integer() | nil,
          :retry_backoff_initial_seconds => integer() | nil,
          :retry_backoff_max_seconds => integer() | nil,
          :attempt_timeout_seconds => integer() | nil,
          :max_response_payload_kbs => integer() | nil,
          :max_concurrent_deliveries => integer() | nil,
          :consecutive_failures => integer() | nil,
          :last_success_at => DateTime.t() | nil,
          :last_failure_at => DateTime.t() | nil,
          :config_hash => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:events, :list, ExBifrost.Model.WebhookEvent)
    |> Deserializer.deserialize(:headers, :map, ExBifrost.Model.WebhookEndpointHeadersValue)
  end
end
