# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.WebhookEndpointWithSecret do
  @moduledoc """
  Returned once when an endpoint is created or its secret is rotated. The secret is shown a single time and cannot be retrieved again. 
  """

  @derive JSON.Encoder
  defstruct [
    :endpoint,
    :secret
  ]

  @type t :: %__MODULE__{
          :endpoint => ExBifrost.Model.WebhookEndpoint.t() | nil,
          :secret => String.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:endpoint, :struct, ExBifrost.Model.WebhookEndpoint)
  end
end
