# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Model.WebhookDeliveryList do
  @moduledoc """
  WebhookDeliveryList model.
  """

  @derive JSON.Encoder
  defstruct [
    :deliveries,
    :pagination
  ]

  @type t :: %__MODULE__{
          :deliveries => [ExBifrost.Model.WebhookDelivery.t()] | nil,
          :pagination => ExBifrost.Model.WebhookDeliveryListPagination.t() | nil
        }

  alias ExBifrost.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:deliveries, :list, ExBifrost.Model.WebhookDelivery)
    |> Deserializer.deserialize(:pagination, :struct, ExBifrost.Model.WebhookDeliveryListPagination)
  end
end
