# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Application do
  @moduledoc """
  OTP application for ExBifrost.

  Starts the Finch HTTP connection pool used by the default
  `ExBifrost.Connection` adapter.

  Pool settings can be tuned via application configuration:

      config :ex_bifrost,
        pool_size: 25,
        pool_count: 1,
        connect_timeout: 5_000
  """

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      {Finch, name: ExBifrost.Finch, pools: pool_config()}
    ]

    Supervisor.start_link(children, strategy: :one_for_one, name: ExBifrost.Supervisor)
  end

  defp pool_config do
    app = :ex_bifrost

    %{
      default: [
        size: Application.get_env(app, :pool_size, 25),
        count: Application.get_env(app, :pool_count, 1),
        conn_opts: [
          transport_opts: [
            timeout: Application.get_env(app, :connect_timeout, 5_000)
          ]
        ]
      ]
    }
  end
end
