# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Connection do
  @moduledoc """
  Handle Tesla connections for ExBifrost.

  Extends the stock openapi-generator connection with production defaults:

    * Connection pooling via Finch (see `ExBifrost.Application`)
    * Per-request timeouts
    * Automatic retries with exponential backoff (idempotent requests only)
    * Telemetry events via `Tesla.Middleware.Telemetry`

  Additional middleware and an alternative adapter can be set in the
  compile-time or runtime configuration:

      config :tesla, ExBifrost.Connection,
        base_url: "http://localhost:8080",
        adapter: Tesla.Adapter.Hackney

  The default base URL can also be set as:

      config :ex_bifrost,
        :base_url, "http://localhost:8080"
  """

  @default_base_url Application.compile_env(
                      :ex_bifrost,
                      :base_url,
                      "http://localhost:8080"
                    )

  @default_timeout 30_000

  # Retry only requests that are safe to replay automatically.
  @idempotent_methods [:get, :head, :options, :put, :delete]
  @retriable_statuses [408, 429, 500, 502, 503, 504]

  @typedoc """
  The list of options that can be passed to new/1.

  - `base_url`: Overrides the base URL on a per-client basis.
  - `user_agent`: Overrides the User-Agent header.
  - `adapter`: Overrides the Tesla adapter (defaults to Finch).
  - `timeout`: Per-request timeout in milliseconds (default: 30_000).
  - `retry`: Retry configuration keyword list, or `false` to disable retries.
    - `max_retries`: Maximum number of retries (default: 3)
    - `delay`: Initial backoff delay in milliseconds (default: 100)
    - `max_delay`: Maximum backoff delay in milliseconds (default: 5_000)
    - `should_retry`: Custom arity-3 retry predicate
  - `middleware`: Additional Tesla middleware (appended to the stack).
  - `username`: A username for basic authentication.
  - `password`: A password for basic authentication.
  - `bearer_token`: A bearer token for bearer authentication.
  """
  @type options :: [
          {:base_url, String.t()},
          {:user_agent, String.t()},
          {:adapter, Tesla.Client.adapter()},
          {:timeout, non_neg_integer()},
          {:retry, keyword() | false},
          {:middleware, [Tesla.Client.middleware()]},
          {:username, String.t() | nil},
          {:password, String.t() | nil},
          {:bearer_token, String.t() | nil}
        ]

  @doc "Forward requests to Tesla."
  @spec request(Tesla.Client.t(), [Tesla.option()]) :: Tesla.Env.result()
  defdelegate request(client, options), to: Tesla

  @doc """
  Configure a ExBifrost client.

  ### Parameters

  - `options`: an optional keyword list of ExBifrost.Connection.options.

  ### Returns

  Tesla.Env.client
  """
  @spec new(options) :: Tesla.Env.client()
  def new(options \\ []) do
    adapter = Keyword.get(options, :adapter, adapter())

    options
    |> middleware()
    |> Tesla.client(adapter)
  end

  @doc """
  Returns fully configured middleware for passing to Tesla.client/2.
  """
  @spec middleware(options) :: [Tesla.Client.middleware()]
  def middleware(options \\ []) do
    app = :ex_bifrost

    base_url =
      Keyword.get(options, :base_url, Application.get_env(app, :base_url, @default_base_url))

    tesla_options = Application.get_env(:tesla, __MODULE__, [])

    middleware =
      Keyword.get(tesla_options, :middleware, []) ++ Keyword.get(options, :middleware, [])

    json_engine = Keyword.get(tesla_options, :json, JSON)

    timeout = Keyword.get(options, :timeout, Application.get_env(app, :timeout, @default_timeout))

    retry_opts = Keyword.get(options, :retry, Application.get_env(app, :retry, []))

    user_agent =
      Keyword.get(
        options,
        :user_agent,
        Keyword.get(
          tesla_options,
          :user_agent,
          "openapi-generator - ExBifrost 0.1.0 - elixir"
        )
      )

    username = Keyword.get(options, :username)
    password = Keyword.get(options, :password)

    middleware =
      if username || password do
        [{Tesla.Middleware.BasicAuth, %{username: username, password: password}} | middleware]
      else
        middleware
      end

    bearer_token = Keyword.get(options, :bearer_token)
    middleware = [{Tesla.Middleware.BearerAuth, token: bearer_token} | middleware]

    [
      {Tesla.Middleware.BaseUrl, base_url},
      {Tesla.Middleware.Headers, [{"user-agent", user_agent}]},
      {Tesla.Middleware.EncodeJson, engine: json_engine},
      {Tesla.Middleware.Telemetry, metadata: %{client: __MODULE__}}
    ] ++
      retry_middleware(retry_opts) ++
      [{Tesla.Middleware.Timeout, timeout: timeout}] ++
      middleware
  end

  @doc """
  Returns the default adapter for this API.

  Defaults to Finch (pooled by `ExBifrost.Application`) and can be
  overridden with:

      config :tesla, ExBifrost.Connection, adapter: Tesla.Adapter.Hackney
  """
  def adapter do
    :tesla
    |> Application.get_env(__MODULE__, [])
    |> Keyword.get(:adapter, {Tesla.Adapter.Finch, name: ExBifrost.Finch})
  end

  defp retry_middleware(false), do: []

  defp retry_middleware(opts) when is_list(opts) do
    [
      {Tesla.Middleware.Retry,
       delay: Keyword.get(opts, :delay, 100),
       max_retries: Keyword.get(opts, :max_retries, 3),
       max_delay: Keyword.get(opts, :max_delay, 5_000),
       should_retry: Keyword.get(opts, :should_retry, &default_should_retry/3)}
    ]
  end

  # Retries are limited to idempotent HTTP methods so that requests with side
  # effects (e.g. POST) are never replayed automatically.
  defp default_should_retry({:ok, %{status: status}}, %{method: method}, _context)
       when status in @retriable_statuses and method in @idempotent_methods,
       do: true

  defp default_should_retry({:ok, _env}, _original_env, _context), do: false

  defp default_should_retry({:error, _reason}, %{method: method}, _context),
    do: method in @idempotent_methods
end
