# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Api.CursorIntegration do
  @moduledoc """
  API calls for all endpoints tagged `CursorIntegration`.
  """

  alias ExBifrost.Connection
  import ExBifrost.RequestBuilder

  @doc """
  Anthropic complete (Cursor mount)
  Cursor mount of the legacy Anthropic `POST /v1/complete` endpoint.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `anthropic_text_request` (AnthropicTextRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.AnthropicCreateComplete200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_anthropic_complete(Tesla.Env.client(), ExBifrost.Model.AnthropicTextRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.AnthropicCreateComplete200Response.t()} | {:error, Tesla.Env.t()}
  def cursor_anthropic_complete(connection, anthropic_text_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v1/complete")
      |> add_param(:body, :body, anthropic_text_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.AnthropicCreateComplete200Response}
    ])
  end

  @doc """
  Anthropic count tokens (Cursor mount)
  Cursor mount of `POST /anthropic/v1/messages/count_tokens`.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `anthropic_message_request` (AnthropicMessageRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_anthropic_count_tokens(Tesla.Env.client(), ExBifrost.Model.AnthropicMessageRequest.t(), keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_anthropic_count_tokens(connection, anthropic_message_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v1/messages/count_tokens")
      |> add_param(:body, :body, anthropic_message_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Anthropic messages (Cursor mount)
  Cursor mount of `POST /anthropic/v1/messages`. Same request/response shape and streaming behaviour.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `anthropic_message_request` (AnthropicMessageRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.AnthropicMessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_anthropic_messages(Tesla.Env.client(), ExBifrost.Model.AnthropicMessageRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.AnthropicCreateMessage400Response.t()}
          | {:ok, ExBifrost.Model.AnthropicMessageResponse.t()}
          | {:error, Tesla.Env.t()}
  def cursor_anthropic_messages(connection, anthropic_message_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v1/messages")
      |> add_param(:body, :body, anthropic_message_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.AnthropicMessageResponse},
      {400, ExBifrost.Model.AnthropicCreateMessage400Response},
      {500, ExBifrost.Model.AnthropicCreateMessage400Response}
    ])
  end

  @doc """
  Anthropic messages — wildcard (Cursor mount)
  Cursor mount of the Anthropic messages wildcard (`POST /anthropic/v1/messages/{path}`). Routes extended Anthropic messages endpoints (e.g. batches, count tokens) through Cursor. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `path` (String.t): 
  - `anthropic_message_request` (AnthropicMessageRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.AnthropicMessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_anthropic_messages_wildcard(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.AnthropicMessageRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.AnthropicCreateMessage400Response.t()}
          | {:ok, ExBifrost.Model.AnthropicMessageResponse.t()}
          | {:error, Tesla.Env.t()}
  def cursor_anthropic_messages_wildcard(connection, path, anthropic_message_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v1/messages/#{path}")
      |> add_param(:body, :body, anthropic_message_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.AnthropicMessageResponse},
      {400, ExBifrost.Model.AnthropicCreateMessage400Response},
      {500, ExBifrost.Model.AnthropicCreateMessage400Response}
    ])
  end

  @doc """
  Bedrock converse (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model_id` (String.t): 
  - `bedrock_converse_request` (BedrockConverseRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.BedrockConverseResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_bedrock_converse(Tesla.Env.client(), String.t(), ExBifrost.Model.BedrockConverseRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BedrockConverseResponse.t()} | {:error, Tesla.Env.t()}
  def cursor_bedrock_converse(connection, model_id, bedrock_converse_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/model/#{model_id}/converse")
      |> add_param(:body, :body, bedrock_converse_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.BedrockConverseResponse}
    ])
  end

  @doc """
  Bedrock converse stream (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model_id` (String.t): 
  - `bedrock_converse_request` (BedrockConverseRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_bedrock_converse_stream(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.BedrockConverseRequest.t(),
          keyword()
        ) :: {:ok, String.t()} | {:error, Tesla.Env.t()}
  def cursor_bedrock_converse_stream(connection, model_id, bedrock_converse_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/model/#{model_id}/converse-stream")
      |> add_param(:body, :body, bedrock_converse_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Bedrock count tokens (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model_id` (String.t): 
  - `cursor_bedrock_count_tokens_request` (CursorBedrockCountTokensRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.BedrockCountTokens200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_bedrock_count_tokens(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.CursorBedrockCountTokensRequest.t(),
          keyword()
        ) :: {:ok, ExBifrost.Model.BedrockCountTokens200Response.t()} | {:error, Tesla.Env.t()}
  def cursor_bedrock_count_tokens(connection, model_id, cursor_bedrock_count_tokens_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/model/#{model_id}/count-tokens")
      |> add_param(:body, :body, cursor_bedrock_count_tokens_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.BedrockCountTokens200Response}
    ])
  end

  @doc """
  Bedrock invoke (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model_id` (String.t): 
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_bedrock_invoke(Tesla.Env.client(), String.t(), %{optional(String.t()) => any()}, keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_bedrock_invoke(connection, model_id, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/model/#{model_id}/invoke")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Bedrock invoke-with-response-stream (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model_id` (String.t): 
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_bedrock_invoke_stream(Tesla.Env.client(), String.t(), %{optional(String.t()) => any()}, keyword()) ::
          {:ok, String.t()} | {:error, Tesla.Env.t()}
  def cursor_bedrock_invoke_stream(connection, model_id, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/model/#{model_id}/invoke-with-response-stream")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Bedrock rerank (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_bedrock_rerank(Tesla.Env.client(), %{optional(String.t()) => any()}, keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_bedrock_rerank(connection, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/rerank")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Cursor hybrid chat completions
  Accepts Cursor's hybrid chat-completions payload (which is structurally a Responses API request with `input` blocks) and returns a chat- completions-shaped response (`choices` + `delta` chunks for streams). Routes the request through the Responses pipeline internally. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `open_ai_responses_request` (OpenAiResponsesRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.ChatCompletionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_chat_completions(Tesla.Env.client(), ExBifrost.Model.OpenAiResponsesRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.ChatCompletionResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def cursor_chat_completions(connection, open_ai_responses_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v1/chat/completions")
      |> add_param(:body, :body, open_ai_responses_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ChatCompletionResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Cohere chat (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_cohere_chat(Tesla.Env.client(), %{optional(String.t()) => any()}, keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_cohere_chat(connection, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v2/chat")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Cohere embed (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_cohere_embed(Tesla.Env.client(), %{optional(String.t()) => any()}, keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_cohere_embed(connection, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v2/embed")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Cohere rerank (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_cohere_rerank(Tesla.Env.client(), %{optional(String.t()) => any()}, keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_cohere_rerank(connection, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v2/rerank")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Cohere tokenize (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_cohere_tokenize(Tesla.Env.client(), %{optional(String.t()) => any()}, keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_cohere_tokenize(connection, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v1/tokenize")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Gemini list models (Cursor mount)
  Cursor mount of `GET /genai/v1beta/models`.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_gemini_list_models(Tesla.Env.client(), keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_gemini_list_models(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/cursor/v1beta/models")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Gemini model action (Cursor mount)
  Cursor mount of Gemini's wildcard generate-content/embed/count-tokens/ predict endpoints. The `model` path parameter includes the action suffix (e.g. `gemini-pro:generateContent`). 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model` (String.t): Model name optionally followed by an action suffix.
  - `gemini_generation_request` (GeminiGenerationRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GeminiGenerationResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_gemini_model_action(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.GeminiGenerationRequest.t(),
          keyword()
        ) :: {:ok, ExBifrost.Model.GeminiGenerationResponse.t()} | {:error, Tesla.Env.t()}
  def cursor_gemini_model_action(connection, model, gemini_generation_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v1beta/models/#{model}")
      |> add_param(:body, :body, gemini_generation_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GeminiGenerationResponse}
    ])
  end

  @doc """
  Gemini video operation polling (Cursor mount)

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model` (String.t): 
  - `operation_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_gemini_retrieve_video_operation(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_gemini_retrieve_video_operation(connection, model, operation_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/cursor/v1beta/models/#{model}/operations/#{operation_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  List models (Cursor)
  Lists available models, returning the OpenAI `/v1/models` shape.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_list_models(Tesla.Env.client(), keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:ok, ExBifrost.Model.BifrostError.t()} | {:error, Tesla.Env.t()}
  def cursor_list_models(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/cursor/v1/models")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Vertex rank (Cursor mount)
  Cursor mount of `POST /genai/v1/rank` — Vertex AI ranking.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec cursor_vertex_rank(Tesla.Env.client(), %{optional(String.t()) => any()}, keyword()) ::
          {:ok, %{optional(String.t()) => any()}} | {:error, Tesla.Env.t()}
  def cursor_vertex_rank(connection, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/cursor/v1/rank")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end
end
