# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Api.Governance do
  @moduledoc """
  API calls for all endpoints tagged `Governance`.
  """

  alias ExBifrost.Connection
  import ExBifrost.RequestBuilder

  @doc """
  Assign team to business unit
  Assigns an existing team to the business unit. Returns 409 if the team is already assigned to a different business unit. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Business unit ID
  - `assign_team_to_business_unit_request` (AssignTeamToBusinessUnitRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec assign_team_to_business_unit(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.AssignTeamToBusinessUnitRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.MessageResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def assign_team_to_business_unit(connection, id, assign_team_to_business_unit_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/business-units/#{id}/teams")
      |> add_param(:body, :body, assign_team_to_business_unit_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {409, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create business unit
  Creates a new business unit. Names must be unique.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `create_team_request` (CreateTeamRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.CreateTeam200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_business_unit(Tesla.Env.client(), ExBifrost.Model.CreateTeamRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.CreateTeam200Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def create_business_unit(connection, create_team_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/business-units")
      |> add_param(:body, :body, create_team_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.CreateTeam200Response},
      {400, ExBifrost.Model.BifrostError},
      {409, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create business unit governance
  Configures budget and/or rate limit governance for a business unit. At least one of `budget` or `rate_limit` is required. Returns 409 if the business unit already has governance configured (use PUT to update). 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Business unit ID
  - `create_business_unit_governance_request` (CreateBusinessUnitGovernanceRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.CreateBusinessUnitGovernance200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_business_unit_governance(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.CreateBusinessUnitGovernanceRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:ok, ExBifrost.Model.CreateBusinessUnitGovernance200Response.t()}
          | {:error, Tesla.Env.t()}
  def create_business_unit_governance(connection, id, create_business_unit_governance_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/business-units/#{id}/governance")
      |> add_param(:body, :body, create_business_unit_governance_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.CreateBusinessUnitGovernance200Response},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {409, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create customer
  Creates a new customer.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `create_customer_request` (CreateCustomerRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.CustomerResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_customer(Tesla.Env.client(), ExBifrost.Model.CreateCustomerRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.CustomerResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def create_customer(connection, create_customer_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/customers")
      |> add_param(:body, :body, create_customer_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.CustomerResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create team
  Creates a new team.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `create_team_request` (CreateTeamRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.TeamResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_governance_team(Tesla.Env.client(), ExBifrost.Model.CreateTeamRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.TeamResponse.t()} | {:ok, ExBifrost.Model.BifrostError.t()} | {:error, Tesla.Env.t()}
  def create_governance_team(connection, create_team_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/teams")
      |> add_param(:body, :body, create_team_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.TeamResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create model config
  Creates a new model configuration with budget and rate limit settings.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `create_model_config_request` (CreateModelConfigRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.ModelConfigResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_model_config(Tesla.Env.client(), ExBifrost.Model.CreateModelConfigRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ModelConfigResponse.t()}
          | {:error, Tesla.Env.t()}
  def create_model_config(connection, create_model_config_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/model-configs")
      |> add_param(:body, :body, create_model_config_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ModelConfigResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create pricing override
  Creates a new pricing override. The most specific matching scope always wins during cost resolution.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `create_pricing_override_request` (CreatePricingOverrideRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.PricingOverrideResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_pricing_override(Tesla.Env.client(), ExBifrost.Model.CreatePricingOverrideRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.PricingOverrideResponse.t()}
          | {:error, Tesla.Env.t()}
  def create_pricing_override(connection, create_pricing_override_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/pricing-overrides")
      |> add_param(:body, :body, create_pricing_override_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExBifrost.Model.PricingOverrideResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create routing rule
  Creates a new CEL-based routing rule for intelligent request routing. Provider and model can be left empty to use the incoming request values.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `create_routing_rule_request` (CreateRoutingRuleRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.RoutingRuleResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_routing_rule(Tesla.Env.client(), ExBifrost.Model.CreateRoutingRuleRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.RoutingRuleResponse.t()}
          | {:error, Tesla.Env.t()}
  def create_routing_rule(connection, create_routing_rule_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/routing-rules")
      |> add_param(:body, :body, create_routing_rule_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.RoutingRuleResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create virtual key
  Creates a new virtual key with the specified configuration.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `create_virtual_key_request` (CreateVirtualKeyRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.VirtualKeyResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_virtual_key(Tesla.Env.client(), ExBifrost.Model.CreateVirtualKeyRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.VirtualKeyResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def create_virtual_key(connection, create_virtual_key_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/virtual-keys")
      |> add_param(:body, :body, create_virtual_key_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.VirtualKeyResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete business unit
  Deletes a business unit. Any teams assigned to it are atomically unassigned as part of the deletion. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Business unit ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_business_unit(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def delete_business_unit(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/business-units/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete business unit governance
  Removes all budget and rate limit governance from a business unit.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Business unit ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_business_unit_governance(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def delete_business_unit_governance(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/business-units/#{id}/governance")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete customer
  Deletes a customer.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `customer_id` (String.t): Customer ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_customer(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def delete_customer(connection, customer_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/customers/#{customer_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete team
  Deletes a team.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `team_id` (String.t): Team ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_governance_team(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def delete_governance_team(connection, team_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/teams/#{team_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete model config
  Deletes a model configuration.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `mc_id` (String.t): Model config ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_model_config(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()} | {:ok, ExBifrost.Model.BifrostError.t()} | {:error, Tesla.Env.t()}
  def delete_model_config(connection, mc_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/model-configs/#{mc_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete pricing override
  Deletes a pricing override by ID.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Pricing override ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_pricing_override(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()} | {:ok, ExBifrost.Model.BifrostError.t()} | {:error, Tesla.Env.t()}
  def delete_pricing_override(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/pricing-overrides/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete provider governance
  Removes governance settings (budget and rate limits) for a specific provider.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `provider_name` (String.t): Provider name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_provider_governance(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()} | {:ok, ExBifrost.Model.BifrostError.t()} | {:error, Tesla.Env.t()}
  def delete_provider_governance(connection, provider_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/providers/#{provider_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete routing rule
  Deletes a routing rule.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `rule_id` (String.t): Routing rule ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_routing_rule(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()} | {:ok, ExBifrost.Model.BifrostError.t()} | {:error, Tesla.Env.t()}
  def delete_routing_rule(connection, rule_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/routing-rules/#{rule_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Delete virtual key
  Deletes a virtual key.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `vk_id` (String.t): Virtual key ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_virtual_key(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()} | {:ok, ExBifrost.Model.BifrostError.t()} | {:error, Tesla.Env.t()}
  def delete_virtual_key(connection, vk_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/virtual-keys/#{vk_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Get business unit
  Returns a specific business unit by ID, including governance and team count.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Business unit ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GetBusinessUnit200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_business_unit(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.GetBusinessUnit200Response.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def get_business_unit(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/governance/business-units/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetBusinessUnit200Response},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Get complexity analyzer config
  Returns the full complexity analyzer runtime config, including tier thresholds and editable keyword lists. Returns built-in defaults if none have been configured.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GetComplexityAnalyzerConfig200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_complexity_analyzer_config(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.GetComplexityAnalyzerConfig200Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def get_complexity_analyzer_config(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/governance/complexity-analyzer-config")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetComplexityAnalyzerConfig200Response},
      {500, ExBifrost.Model.BifrostError},
      {503, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Get customer
  Returns a specific customer by ID.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `customer_id` (String.t): Customer ID
  - `opts` (keyword): Optional parameters
    - `:from_memory` (boolean()): If true, returns customer from in-memory cache instead of database

  ### Returns

  - `{:ok, ExBifrost.Model.GetCustomer200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_customer(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.GetCustomer200Response.t()}
          | {:error, Tesla.Env.t()}
  def get_customer(connection, customer_id, opts \\ []) do
    optional_params = %{
      :from_memory => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/customers/#{customer_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetCustomer200Response},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Get team
  Returns a specific team by ID.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `team_id` (String.t): Team ID
  - `opts` (keyword): Optional parameters
    - `:from_memory` (boolean()): If true, returns team from in-memory cache instead of database

  ### Returns

  - `{:ok, ExBifrost.Model.GetGovernanceTeam200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_governance_team(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.GetGovernanceTeam200Response.t()}
          | {:error, Tesla.Env.t()}
  def get_governance_team(connection, team_id, opts \\ []) do
    optional_params = %{
      :from_memory => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/teams/#{team_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetGovernanceTeam200Response},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Get model config
  Returns a specific model configuration by ID.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `mc_id` (String.t): Model config ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GetModelConfig200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_model_config(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.GetModelConfig200Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def get_model_config(connection, mc_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/governance/model-configs/#{mc_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetModelConfig200Response},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Get routing rule
  Returns a specific routing rule by ID.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `rule_id` (String.t): Routing rule ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GetRoutingRule200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_routing_rule(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.GetRoutingRule200Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def get_routing_rule(connection, rule_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/governance/routing-rules/#{rule_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetRoutingRule200Response},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Get virtual key
  Returns a specific virtual key by ID.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `vk_id` (String.t): Virtual key ID
  - `opts` (keyword): Optional parameters
    - `:from_memory` (boolean()): If true, returns virtual key from in-memory cache instead of database

  ### Returns

  - `{:ok, ExBifrost.Model.GetVirtualKey200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_virtual_key(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.GetVirtualKey200Response.t()}
          | {:error, Tesla.Env.t()}
  def get_virtual_key(connection, vk_id, opts \\ []) do
    optional_params = %{
      :from_memory => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/virtual-keys/#{vk_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetVirtualKey200Response},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Get virtual key quota
  Returns the overall budget and rate limit quota for the authenticated virtual key, as well as per-provider and per-model budgets and rate limits (with current usage). Each budget also carries the actual per-model usage for its current cycle. This is a self-service endpoint - no admin authentication required. The virtual key value itself (provided via header) is the credential. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.VirtualKeyQuotaResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_virtual_key_quota(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.GetVirtualKeyQuota401Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.VirtualKeyQuotaResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_virtual_key_quota(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/governance/virtual-keys/quota")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.VirtualKeyQuotaResponse},
      {401, ExBifrost.Model.GetVirtualKeyQuota401Response},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List budgets
  Returns a list of all budgets. Use the `from_memory` query parameter to get data from in-memory cache.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:from_memory` (boolean()): If true, returns budgets from in-memory cache instead of database

  ### Returns

  - `{:ok, ExBifrost.Model.ListBudgetsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_budgets(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.ListBudgetsResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def list_budgets(connection, opts \\ []) do
    optional_params = %{
      :from_memory => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/budgets")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListBudgetsResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List business unit teams
  Returns a paginated list of teams assigned to the business unit.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Business unit ID
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): Page number (1-based)
    - `:limit` (integer()): Maximum number of teams to return (max 100)
    - `:search` (String.t): Case-insensitive search by team name

  ### Returns

  - `{:ok, ExBifrost.Model.ListBusinessUnitTeams200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_business_unit_teams(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.ListBusinessUnitTeams200Response.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def list_business_unit_teams(connection, id, opts \\ []) do
    optional_params = %{
      :page => :query,
      :limit => :query,
      :search => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/business-units/#{id}/teams")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListBusinessUnitTeams200Response},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List business units
  Returns a paginated list of business units, each with its team count.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): Page number (1-based)
    - `:limit` (integer()): Maximum number of business units to return (max 100)
    - `:search` (String.t): Case-insensitive search by business unit name

  ### Returns

  - `{:ok, ExBifrost.Model.ListBusinessUnits200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_business_units(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.ListBusinessUnits200Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def list_business_units(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :limit => :query,
      :search => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/business-units")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListBusinessUnits200Response},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List customers
  Returns a list of all customers.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:from_memory` (boolean()): If true, returns customers from in-memory cache instead of database

  ### Returns

  - `{:ok, ExBifrost.Model.ListCustomersResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_customers(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.ListCustomersResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def list_customers(connection, opts \\ []) do
    optional_params = %{
      :from_memory => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/customers")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListCustomersResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List teams
  Returns a list of all teams.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:customer_id` (String.t): Filter teams by customer ID
    - `:from_memory` (boolean()): If true, returns teams from in-memory cache instead of database

  ### Returns

  - `{:ok, ExBifrost.Model.ListTeamsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_governance_teams(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ListTeamsResponse.t()}
          | {:error, Tesla.Env.t()}
  def list_governance_teams(connection, opts \\ []) do
    optional_params = %{
      :customer_id => :query,
      :from_memory => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/teams")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListTeamsResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List model limits
  Returns a paginated list of model limits with their budget and rate limit settings.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): Maximum number of results to return
    - `:offset` (integer()): Number of results to skip (for pagination)
    - `:search` (String.t): Case-insensitive filter by model name
    - `:scope` (String.t): Filter by scope (`global`, `virtual_key`, or `user`; `user` is Enterprise only)
    - `:provider` (String.t): Filter by provider name
    - `:from_memory` (boolean()): If true, returns data from in-memory cache (faster, may lag DB by one poll cycle)

  ### Returns

  - `{:ok, ExBifrost.Model.ListModelConfigsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_model_configs(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.ListModelConfigsResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def list_model_configs(connection, opts \\ []) do
    optional_params = %{
      :limit => :query,
      :offset => :query,
      :search => :query,
      :scope => :query,
      :provider => :query,
      :from_memory => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/model-configs")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListModelConfigsResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List pricing overrides
  Returns all pricing overrides, optionally filtered by scope.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:scope_kind` (String.t): Filter by scope kind
    - `:virtual_key_id` (String.t): Filter by virtual key ID (for virtual_key* scopes)
    - `:provider_id` (String.t): Filter by provider ID
    - `:provider_key_id` (String.t): Filter by provider key ID

  ### Returns

  - `{:ok, ExBifrost.Model.ListPricingOverridesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_pricing_overrides(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ListPricingOverridesResponse.t()}
          | {:error, Tesla.Env.t()}
  def list_pricing_overrides(connection, opts \\ []) do
    optional_params = %{
      :scope_kind => :query,
      :virtual_key_id => :query,
      :provider_id => :query,
      :provider_key_id => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/pricing-overrides")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListPricingOverridesResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List provider governance
  Returns a list of all providers with their governance settings (budget and rate limits).

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.ListProviderGovernanceResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_provider_governance(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.ListProviderGovernanceResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def list_provider_governance(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/governance/providers")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListProviderGovernanceResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List rate limits
  Returns a list of all rate limits. Use the `from_memory` query parameter to get data from in-memory cache.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:from_memory` (boolean()): If true, returns rate limits from in-memory cache instead of database

  ### Returns

  - `{:ok, ExBifrost.Model.ListRateLimitsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_rate_limits(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.ListRateLimitsResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def list_rate_limits(connection, opts \\ []) do
    optional_params = %{
      :from_memory => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/rate-limits")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListRateLimitsResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List routing rules
  Returns a list of all routing rules configured for intelligent request routing across providers.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:scope` (String.t): Filter routing rules by scope (global, team, customer, virtual_key)
    - `:scope_id` (String.t): Filter routing rules by scope ID

  ### Returns

  - `{:ok, ExBifrost.Model.ListRoutingRulesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_routing_rules(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ListRoutingRulesResponse.t()}
          | {:error, Tesla.Env.t()}
  def list_routing_rules(connection, opts \\ []) do
    optional_params = %{
      :scope => :query,
      :scope_id => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/routing-rules")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListRoutingRulesResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List virtual keys
  Returns a list of all virtual keys with their configurations.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:from_memory` (boolean()): If true, returns virtual keys from in-memory cache instead of database
    - `:limit` (integer()): Maximum number of virtual keys to return
    - `:offset` (integer()): Number of virtual keys to skip
    - `:search` (String.t): Case-insensitive search by virtual key name
    - `:customer_id` (String.t): Filter virtual keys by customer ID
    - `:team_id` (String.t): Filter virtual keys by team ID
    - `:sort_by` (String.t): Field to sort by
    - `:order` (String.t): Sort order
    - `:export` (boolean()): If true, enables export pagination limits
    - `:exclude_access_profile_managed_virtual` (boolean()): If true, excludes virtual keys managed by access profiles

  ### Returns

  - `{:ok, ExBifrost.Model.ListVirtualKeysResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_virtual_keys(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.ListVirtualKeysResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def list_virtual_keys(connection, opts \\ []) do
    optional_params = %{
      :from_memory => :query,
      :limit => :query,
      :offset => :query,
      :search => :query,
      :customer_id => :query,
      :team_id => :query,
      :sort_by => :query,
      :order => :query,
      :export => :query,
      :exclude_access_profile_managed_virtual => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/governance/virtual-keys")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ListVirtualKeysResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Remove team from business unit
  Unassigns a team from the business unit.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Business unit ID
  - `team_id` (String.t): Team ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.MessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_team_from_business_unit(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.MessageResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def remove_team_from_business_unit(connection, id, team_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/governance/business-units/#{id}/teams/#{team_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.MessageResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Reset complexity analyzer config
  Restores the built-in complexity analyzer runtime config defaults and hot-reloads the governance plugin.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GetComplexityAnalyzerConfig200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec reset_complexity_analyzer_config(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.GetComplexityAnalyzerConfig200Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def reset_complexity_analyzer_config(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/governance/complexity-analyzer-config/reset")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetComplexityAnalyzerConfig200Response},
      {500, ExBifrost.Model.BifrostError},
      {503, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update business unit governance
  Updates budget and/or rate limit governance for a business unit. Passing an empty `budget` or `rate_limit` object removes that governance component. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Business unit ID
  - `update_business_unit_governance_request` (UpdateBusinessUnitGovernanceRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.UpdateBusinessUnitGovernance200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_business_unit_governance(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.UpdateBusinessUnitGovernanceRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.UpdateBusinessUnitGovernance200Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def update_business_unit_governance(connection, id, update_business_unit_governance_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/business-units/#{id}/governance")
      |> add_param(:body, :body, update_business_unit_governance_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.UpdateBusinessUnitGovernance200Response},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update complexity analyzer config
  Replaces the full complexity analyzer runtime config and hot-reloads the governance plugin. Tier thresholds must satisfy 0 < simple_medium < medium_complex < complex_reasoning < 1.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `get_complexity_analyzer_config200_response` (GetComplexityAnalyzerConfig200Response): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GetComplexityAnalyzerConfig200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_complexity_analyzer_config(
          Tesla.Env.client(),
          ExBifrost.Model.GetComplexityAnalyzerConfig200Response.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.GetComplexityAnalyzerConfig200Response.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def update_complexity_analyzer_config(connection, get_complexity_analyzer_config200_response, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/complexity-analyzer-config")
      |> add_param(:body, :body, get_complexity_analyzer_config200_response)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GetComplexityAnalyzerConfig200Response},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError},
      {503, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update customer
  Updates an existing customer.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `customer_id` (String.t): Customer ID
  - `update_customer_request` (UpdateCustomerRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.CustomerResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_customer(Tesla.Env.client(), String.t(), ExBifrost.Model.UpdateCustomerRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.CustomerResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def update_customer(connection, customer_id, update_customer_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/customers/#{customer_id}")
      |> add_param(:body, :body, update_customer_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.CustomerResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update team
  Updates an existing team.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `team_id` (String.t): Team ID
  - `update_team_request` (UpdateTeamRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.TeamResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_governance_team(Tesla.Env.client(), String.t(), ExBifrost.Model.UpdateTeamRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.TeamResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ManagementErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def update_governance_team(connection, team_id, update_team_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/teams/#{team_id}")
      |> add_param(:body, :body, update_team_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.TeamResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.ManagementErrorResponse},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update model config
  Updates an existing model configuration's budget and rate limit settings.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `mc_id` (String.t): Model config ID
  - `update_model_config_request` (UpdateModelConfigRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.ModelConfigResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_model_config(Tesla.Env.client(), String.t(), ExBifrost.Model.UpdateModelConfigRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.ModelConfigResponse.t()}
          | {:error, Tesla.Env.t()}
  def update_model_config(connection, mc_id, update_model_config_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/model-configs/#{mc_id}")
      |> add_param(:body, :body, update_model_config_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ModelConfigResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update pricing override
  Updates an existing pricing override. Omitted fields are merged from the existing record. The `patch` field is always replaced in full when provided.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `id` (String.t): Pricing override ID
  - `update_pricing_override_request` (UpdatePricingOverrideRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.PricingOverrideResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_pricing_override(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.UpdatePricingOverrideRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.PricingOverrideResponse.t()}
          | {:error, Tesla.Env.t()}
  def update_pricing_override(connection, id, update_pricing_override_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/pricing-overrides/#{id}")
      |> add_param(:body, :body, update_pricing_override_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.PricingOverrideResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update provider governance
  Updates governance settings (budget and rate limits) for a specific provider.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `provider_name` (String.t): Provider name
  - `update_provider_governance_request` (UpdateProviderGovernanceRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.ProviderGovernanceResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_provider_governance(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.UpdateProviderGovernanceRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.ProviderGovernanceResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def update_provider_governance(connection, provider_name, update_provider_governance_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/providers/#{provider_name}")
      |> add_param(:body, :body, update_provider_governance_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ProviderGovernanceResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update routing rule
  Updates an existing routing rule's configuration.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `rule_id` (String.t): Routing rule ID
  - `update_routing_rule_request` (UpdateRoutingRuleRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.RoutingRuleResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_routing_rule(Tesla.Env.client(), String.t(), ExBifrost.Model.UpdateRoutingRuleRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.RoutingRuleResponse.t()}
          | {:error, Tesla.Env.t()}
  def update_routing_rule(connection, rule_id, update_routing_rule_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/routing-rules/#{rule_id}")
      |> add_param(:body, :body, update_routing_rule_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.RoutingRuleResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Update virtual key
  Updates an existing virtual key's configuration.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `vk_id` (String.t): Virtual key ID
  - `update_virtual_key_request` (UpdateVirtualKeyRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.VirtualKeyResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_virtual_key(Tesla.Env.client(), String.t(), ExBifrost.Model.UpdateVirtualKeyRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.VirtualKeyResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def update_virtual_key(connection, vk_id, update_virtual_key_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/governance/virtual-keys/#{vk_id}")
      |> add_param(:body, :body, update_virtual_key_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.VirtualKeyResponse},
      {400, ExBifrost.Model.BifrostError},
      {404, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end
end
