# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Api.Infrastructure do
  @moduledoc """
  API calls for all endpoints tagged `Infrastructure`.
  """

  alias ExBifrost.Connection
  import ExBifrost.RequestBuilder

  @doc """
  Prometheus metrics
  Returns Prometheus-formatted metrics for monitoring.

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_metrics(Tesla.Env.client(), keyword()) :: {:ok, String.t()} | {:error, Tesla.Env.t()}
  def get_metrics(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/metrics")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  MCP protocol message
  Receives a JSON-RPC 2.0 message for the MCP protocol server. Returns a JSON-RPC 2.0 response, or null for notifications. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `mcp_server_message_request` (McpServerMessageRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.McpServerMessage200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec mcp_server_message(Tesla.Env.client(), ExBifrost.Model.McpServerMessageRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.McpServerMessage200Response.t()} | {:error, Tesla.Env.t()}
  def mcp_server_message(connection, mcp_server_message_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/mcp")
      |> add_param(:body, :body, mcp_server_message_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.McpServerMessage200Response}
    ])
  end

  @doc """
  MCP protocol SSE stream
  Opens a Server-Sent Events stream for the MCP protocol server. Returns `Content-Type: text/event-stream`. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec mcp_server_sse(Tesla.Env.client(), keyword()) :: {:ok, String.t()} | {:error, Tesla.Env.t()}
  def mcp_server_sse(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/mcp")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  WebSocket connection
  Upgrades to a WebSocket connection for real-time updates. Server pushes log events, MCP log events, and store update notifications. Heartbeat pings are sent every 30 seconds. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec websocket_connect(Tesla.Env.client(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def websocket_connect(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/ws")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {101, false}
    ])
  end
end
