# NOTE: This file is auto generated by OpenAPI Generator 7.23.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExBifrost.Api.LiteLLMIntegration do
  @moduledoc """
  API calls for all endpoints tagged `LiteLLMIntegration`.
  """

  alias ExBifrost.Connection
  import ExBifrost.RequestBuilder

  @doc """
  Create message (LiteLLM - Anthropic format)
  Creates a message using Anthropic-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `anthropic_message_request` (AnthropicMessageRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.AnthropicMessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_anthropic_messages(Tesla.Env.client(), ExBifrost.Model.AnthropicMessageRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.AnthropicCreateMessage400Response.t()}
          | {:ok, ExBifrost.Model.AnthropicMessageResponse.t()}
          | {:error, Tesla.Env.t()}
  def litellm_anthropic_messages(connection, anthropic_message_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/anthropic/v1/messages")
      |> add_param(:body, :body, anthropic_message_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.AnthropicMessageResponse},
      {400, ExBifrost.Model.AnthropicCreateMessage400Response},
      {500, ExBifrost.Model.AnthropicCreateMessage400Response}
    ])
  end

  @doc """
  Converse with model (LiteLLM - Bedrock format)
  Sends messages using AWS Bedrock Converse-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model_id` (String.t): Model ID
  - `bedrock_converse_request` (BedrockConverseRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.BedrockConverseResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_bedrock_converse(Tesla.Env.client(), String.t(), ExBifrost.Model.BedrockConverseRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BedrockError.t()}
          | {:ok, ExBifrost.Model.BedrockConverseResponse.t()}
          | {:error, Tesla.Env.t()}
  def litellm_bedrock_converse(connection, model_id, bedrock_converse_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/bedrock/model/#{model_id}/converse")
      |> add_param(:body, :body, bedrock_converse_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.BedrockConverseResponse},
      {400, ExBifrost.Model.BedrockError},
      {500, ExBifrost.Model.BedrockError}
    ])
  end

  @doc """
  Stream converse with model (LiteLLM - Bedrock format)
  Streams messages using AWS Bedrock Converse-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model_id` (String.t): Model ID
  - `bedrock_converse_request` (BedrockConverseRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.BedrockConverseStream200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_bedrock_converse_stream(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.BedrockConverseRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.BedrockError.t()}
          | {:ok, ExBifrost.Model.BedrockConverseStream200Response.t()}
          | {:error, Tesla.Env.t()}
  def litellm_bedrock_converse_stream(connection, model_id, bedrock_converse_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/bedrock/model/#{model_id}/converse-stream")
      |> add_param(:body, :body, bedrock_converse_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.BedrockConverseStream200Response},
      {400, ExBifrost.Model.BedrockError},
      {500, ExBifrost.Model.BedrockError}
    ])
  end

  @doc """
  Chat with model (LiteLLM - Cohere format)
  Sends a chat request using Cohere-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `cohere_chat_request` (CohereChatRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.CohereChatResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_cohere_chat(Tesla.Env.client(), ExBifrost.Model.CohereChatRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.CohereChatResponse.t()}
          | {:ok, ExBifrost.Model.CohereError.t()}
          | {:error, Tesla.Env.t()}
  def litellm_cohere_chat(connection, cohere_chat_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/cohere/v2/chat")
      |> add_param(:body, :body, cohere_chat_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.CohereChatResponse},
      {400, ExBifrost.Model.CohereError},
      {500, ExBifrost.Model.CohereError}
    ])
  end

  @doc """
  Create embeddings (LiteLLM - Cohere format)
  Creates embeddings using Cohere-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `cohere_embedding_request` (CohereEmbeddingRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.CohereEmbeddingResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_cohere_embed(Tesla.Env.client(), ExBifrost.Model.CohereEmbeddingRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.CohereEmbeddingResponse.t()}
          | {:ok, ExBifrost.Model.CohereError.t()}
          | {:error, Tesla.Env.t()}
  def litellm_cohere_embed(connection, cohere_embedding_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/cohere/v2/embed")
      |> add_param(:body, :body, cohere_embedding_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.CohereEmbeddingResponse},
      {400, ExBifrost.Model.CohereError},
      {500, ExBifrost.Model.CohereError}
    ])
  end

  @doc """
  Tokenize text (LiteLLM - Cohere format)
  Tokenizes text using Cohere-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `cohere_count_tokens_request` (CohereCountTokensRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.CohereCountTokensResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_cohere_tokenize(Tesla.Env.client(), ExBifrost.Model.CohereCountTokensRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.CohereCountTokensResponse.t()}
          | {:ok, ExBifrost.Model.CohereError.t()}
          | {:error, Tesla.Env.t()}
  def litellm_cohere_tokenize(connection, cohere_count_tokens_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/cohere/v1/tokenize")
      |> add_param(:body, :body, cohere_count_tokens_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.CohereCountTokensResponse},
      {400, ExBifrost.Model.CohereError},
      {500, ExBifrost.Model.CohereError}
    ])
  end

  @doc """
  Generate content (LiteLLM - Gemini format)
  Generates content using Google Gemini-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model` (String.t): Model name with action
  - `gemini_generation_request` (GeminiGenerationRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GeminiGenerationResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_gemini_generate_content(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.GeminiGenerationRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.GeminiError.t()}
          | {:ok, ExBifrost.Model.GeminiGenerationResponse.t()}
          | {:error, Tesla.Env.t()}
  def litellm_gemini_generate_content(connection, model, gemini_generation_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/genai/v1beta/models/#{model}:generateContent")
      |> add_param(:body, :body, gemini_generation_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GeminiGenerationResponse},
      {400, ExBifrost.Model.GeminiError},
      {500, ExBifrost.Model.GeminiError}
    ])
  end

  @doc """
  List models (LiteLLM - Gemini format)
  Lists available models in Google Gemini API format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:pageSize` (integer()): Maximum number of models to return
    - `:pageToken` (String.t): Page token for pagination

  ### Returns

  - `{:ok, ExBifrost.Model.GeminiListModelsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_gemini_list_models(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.GeminiListModelsResponse.t()}
          | {:ok, ExBifrost.Model.GeminiError.t()}
          | {:error, Tesla.Env.t()}
  def litellm_gemini_list_models(connection, opts \\ []) do
    optional_params = %{
      :pageSize => :query,
      :pageToken => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/litellm/genai/v1beta/models")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GeminiListModelsResponse},
      {400, ExBifrost.Model.GeminiError},
      {500, ExBifrost.Model.GeminiError}
    ])
  end

  @doc """
  Stream generate content (LiteLLM - Gemini format)
  Streams content generation using Google Gemini-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model` (String.t): Model name with action
  - `gemini_generation_request` (GeminiGenerationRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.GeminiGenerationResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_gemini_stream_generate_content(
          Tesla.Env.client(),
          String.t(),
          ExBifrost.Model.GeminiGenerationRequest.t(),
          keyword()
        ) ::
          {:ok, ExBifrost.Model.GeminiError.t()}
          | {:ok, ExBifrost.Model.GeminiGenerationResponse.t()}
          | {:error, Tesla.Env.t()}
  def litellm_gemini_stream_generate_content(connection, model, gemini_generation_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/genai/v1beta/models/#{model}:streamGenerateContent")
      |> add_param(:body, :body, gemini_generation_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.GeminiGenerationResponse},
      {400, ExBifrost.Model.GeminiError},
      {500, ExBifrost.Model.GeminiError}
    ])
  end

  @doc """
  Chat completions (LiteLLM - OpenAI format)
  Creates a chat completion using OpenAI-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `open_ai_chat_request` (OpenAiChatRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.ChatCompletionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_open_ai_chat_completions(Tesla.Env.client(), ExBifrost.Model.OpenAiChatRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.ChatCompletionResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def litellm_open_ai_chat_completions(connection, open_ai_chat_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/v1/chat/completions")
      |> add_param(:body, :body, open_ai_chat_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ChatCompletionResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Count input tokens (LiteLLM - OpenAI format)
  Counts the number of tokens in a Responses API request via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `open_ai_responses_request` (OpenAiResponsesRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.CountTokensResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_open_ai_count_input_tokens(Tesla.Env.client(), ExBifrost.Model.OpenAiResponsesRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.CountTokensResponse.t()}
          | {:error, Tesla.Env.t()}
  def litellm_open_ai_count_input_tokens(connection, open_ai_responses_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/v1/responses/input_tokens")
      |> add_param(:body, :body, open_ai_responses_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.CountTokensResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create embeddings (LiteLLM - OpenAI format)
  Creates embeddings using OpenAI-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `open_ai_embedding_request` (OpenAiEmbeddingRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.EmbeddingResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_open_ai_embeddings(Tesla.Env.client(), ExBifrost.Model.OpenAiEmbeddingRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.EmbeddingResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def litellm_open_ai_embeddings(connection, open_ai_embedding_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/v1/embeddings")
      |> add_param(:body, :body, open_ai_embedding_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.EmbeddingResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  List models (LiteLLM - OpenAI format)
  Lists available models using OpenAI-compatible format via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.OpenAiListModelsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_open_ai_list_models(Tesla.Env.client(), keyword()) ::
          {:ok, ExBifrost.Model.OpenAiListModelsResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def litellm_open_ai_list_models(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/litellm/v1/models")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.OpenAiListModelsResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create response (LiteLLM - OpenAI Responses API)
  Creates a response using OpenAI Responses API format via LiteLLM. Supports streaming via SSE. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `open_ai_responses_request` (OpenAiResponsesRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.ResponsesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_open_ai_responses(Tesla.Env.client(), ExBifrost.Model.OpenAiResponsesRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.ResponsesResponse.t()}
          | {:ok, ExBifrost.Model.BifrostError.t()}
          | {:error, Tesla.Env.t()}
  def litellm_open_ai_responses(connection, open_ai_responses_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/v1/responses")
      |> add_param(:body, :body, open_ai_responses_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.ResponsesResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create speech (LiteLLM - OpenAI TTS)
  Generates audio from text using OpenAI TTS via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `open_ai_speech_request` (OpenAiSpeechRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_open_ai_speech(Tesla.Env.client(), ExBifrost.Model.OpenAiSpeechRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()} | {:ok, String.t()} | {:error, Tesla.Env.t()}
  def litellm_open_ai_speech(connection, open_ai_speech_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/v1/audio/speech")
      |> add_param(:body, :body, open_ai_speech_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Text completions (LiteLLM - OpenAI format)
  Creates a text completion using OpenAI-compatible format via LiteLLM. This is the legacy completions API. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `open_ai_text_completion_request` (OpenAiTextCompletionRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExBifrost.Model.TextCompletionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_open_ai_text_completions(Tesla.Env.client(), ExBifrost.Model.OpenAiTextCompletionRequest.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.TextCompletionResponse.t()}
          | {:error, Tesla.Env.t()}
  def litellm_open_ai_text_completions(connection, open_ai_text_completion_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/litellm/v1/completions")
      |> add_param(:body, :body, open_ai_text_completion_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.TextCompletionResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end

  @doc """
  Create transcription (LiteLLM - OpenAI Whisper)
  Transcribes audio into text using OpenAI Whisper via LiteLLM. 

  ### Parameters

  - `connection` (ExBifrost.Connection): Connection to server
  - `model` (String.t): Model identifier (e.g., whisper-1)
  - `file` (String.t): Audio file to transcribe
  - `opts` (keyword): Optional parameters
    - `:language` (String.t): Language of the audio (ISO 639-1)
    - `:prompt` (String.t): Prompt to guide transcription
    - `:response_format` (String.t): 
    - `:temperature` (number()): 
    - `:timestamp_granularities` ([String.t]): 
    - `:stream` (boolean()): 
    - `:fallbacks` ([String.t]): 

  ### Returns

  - `{:ok, ExBifrost.Model.TranscriptionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec litellm_open_ai_transcriptions(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, ExBifrost.Model.BifrostError.t()}
          | {:ok, ExBifrost.Model.TranscriptionResponse.t()}
          | {:error, Tesla.Env.t()}
  def litellm_open_ai_transcriptions(connection, model, file, opts \\ []) do
    optional_params = %{
      :language => :form,
      :prompt => :form,
      :response_format => :form,
      :temperature => :form,
      :timestamp_granularities => :form,
      :stream => :form,
      :fallbacks => :form
    }

    request =
      %{}
      |> method(:post)
      |> url("/litellm/v1/audio/transcriptions")
      |> add_param(:form, :model, model)
      |> add_param(:file, :file, file)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExBifrost.Model.TranscriptionResponse},
      {400, ExBifrost.Model.BifrostError},
      {500, ExBifrost.Model.BifrostError}
    ])
  end
end
